### ISSUE TITLE
Add examples how to use the other parts of firebase (e.g. firestore) with this package / Best practice

### ISSUE THREAD

**Issue by SelfDevTV** [gladly-team/next-firebase-auth#113]
**Is your feature request related to a problem? Please describe.**
No problem, it's just a few improvements for the docs

**Describe the solution you'd like and how you'd implement it**
So I used the package the first time yesterday. Everything works perfectly.**Nice library good job guys :)** I was just missing 1 or 2 examples of how to use firebase parts inside this package. For example how to add a logged in user into the firestore database. Like best practice examples where it's best to do this. 

Right now when a user loggs in I added him to the database like so:

```
import React, { useEffect } from "react";
import {
  useAuthUser,
  withAuthUser,
  withAuthUserTokenSSR,
} from "next-firebase-auth";
import firebase from "firebase";

const Demo = () => {
  const AuthUser = useAuthUser();

  useEffect(() => {
    console.log(AuthUser);
  });

  const login = () => {
    var provider = new firebase.auth.FacebookAuthProvider();
    firebase
      .auth()
      .signInWithPopup(provider)
      .then((result) => {
        console.log(result);
        firebase.firestore().collection("users").doc(result.user.email).set({
          email: result.user.email,
          displayName: result.user.displayName,
        });
      });
  };

  const logout = () => {
    firebase.auth().signOut();
  };

  return (
    <div>
      <p>Your email is {AuthUser.email ? AuthUser.email : "unknown"}.</p>

      <button onClick={() => login()}>Login</button>
      <button onClick={() => logout()}>Logout</button>
    </div>
  );
};

// Note that this is a higher-order function.
export const getServerSideProps = withAuthUserTokenSSR()();

export default withAuthUser()(Demo);
```

Is this a good way to handle this scenario? Or should this be handled on the server side in an api route?

**Comment by kmjennison** [comment]
Your approach looks reasonable to me. In general, you can use Firebase on the client side how you normally would.

If you need to access the Firebase apps, you can let `next-firebase-auth` initialize them and import them like you do here. Alternatively, you can initialize them yourself in your own modules: see [this comment](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977) for an example. Would it help to add something like this discussion comment to the documentation, such as "How to use the Firebase JS or admin app"?

I'm also open to suggestions on how we can make this a little more intuitive without adding complexity/props to this package.

**Comment by kmjennison** [comment]
Added the above recommendation to the README and opened this RFC: https://github.com/gladly-team/next-firebase-auth/issues/135
