### ISSUE TITLE
More documentation on custom claims

### ISSUE THREAD

**Issue by AndreasJacobsen** [gladly-team/next-firebase-auth#118]
**Is your feature request related to a problem? Please describe.**
This project is now the officially linked project from the NextJS docs for Firebase auth (congratulations!). The README page of this project tells us 

>Supporting custom claims: Currently, the AuthUser object does not include any Firebase custom claims.

Now I have already spent a bunch of time getting this package to work, and saw this too late. Now I'm considering a re-write without this package because I need custom claims in order to check what a user should have access too (this is what I have interpreted custom claims to be for). 

I am also what you would call a 'noob'-programmer, and I suspect that you actually can use custom claims with this package. You can just not get the results through AuthUser 

**Describe the solution you'd like and how you'd implement it**
Implement an example where where firebase custom claims are used, and an example where they are set (if possible). Through the API or any other method. 

**Describe alternatives you've considered**
firebase NPM package, how ever this has pretty much no documentation on how to handle things server side or how to use the package with NextJS.

**Comment by kmjennison** [comment]
Hi, thanks! I'm hopeful we'll have a contribution to support custom claims in this package soon. See PR #109 and discussion #104.

If you need it urgently, you can likely fork this package and add the (pretty straightforward) changes from #109, though that's currently untested. Alternatively, you could get the custom claims on the client, set them in a cookie with something like `js-cookie`, and grab that cookie on the server side.
