### ISSUE TITLE
Property "firebaseUser" on "AuthUser" is null even though the token is valid and returns a user.

### ISSUE THREAD

**Issue by maxzaleski** [gladly-team/next-firebase-auth#119]
**Describe the bug**

The bug occurred during the use of  `withAuthUserTokenSSR`.

The property `firebaseUser` on the object `AuthUser` returns `null` even though the token is valid and returns a user.

Here's a log output of `AuthUser.user`:

```Typescript
{
  id: '*redacted*',
  email: '*redacted*',
  emailVerified: true,
  getIdToken: [Function (anonymous)],
  clientInitialized: false,
  firebaseUser: null,
  signOut: [Function (anonymous)],
  serialize: [Function: serialize]
}
```

**Version**
v0.12.2

**To Reproduce/Context**

> A snippet is more pertinent.

```Typescript
... = withAuthUserTokenSSR()(async ({ AuthUser: user, ...ctx }) => {
    if (!user || !user.id) {
      const { resolvedUrl } = ctx;
      const path = resolvedUrl.match(/^(\/[a-z|\/]+)?/)[0];
      return {
        redirect: {
          statusCode: 301,
          destination:
            path && path != PATH_LOGOUT
              ? PATH_LOGIN + `?${QUERY_KEY_REDIRECT_TO}=${path.replace(/\//g, '%2F')}`
              : PATH_LOGIN,
        },
        props: {} as never,
      };
    }

    const token = await user.getIdToken();
>   const { claims } = await user.firebaseUser.getIdTokenResult();

    const result = await Promise.all([
      apiRequest<IOrganisation>({
        url: API_BASE_SERVICE_PATH_ORGANISATION,
        method: 'GET',
        token,
      }),
      apiRequest<IMember>({
        url: `${API_BASE_SERVICE_PATH_MEMBERS}/${claims.member_id}`,
        method: 'GET',
        token,
      }),
    ])

    return {
      props: {
        currentOrg: result[0].data,
        currentMember: result[1].data,
      }
    }
  });
```

**Expected behavior**
The property `firebaseUser` is present on the `AuthUser` object.

**Comment by kmjennison** [comment]
This is expected, because the `firebaseUser` is only set on the client side. From [docs](https://github.com/gladly-team/next-firebase-auth#authuser), "The user from the Firebase JS SDK, if it has initialized. Otherwise, null."

It looks like you're trying to access custom claims, which will hopefully be supported soon (see #109).

**Comment by maxzaleski** [comment]
@kmjennison Ah, I see. Will keep an eye out. Thank you.

**Comment by jeffersonlicet** [comment]
Hi, this is happening now with the canary version, AuthUser is sometimes null, and getIdToken() is also null. Any workaround? Thanks (I'm using withAuthUserTokenSSR) The odd thing is that when the user comes from a redirect of another web (and is logged in my web) it appears the first time as logged out, if I refresh, it's now logged in.

**Comment by kmjennison** [comment]
@jeffersonlicet That behavior might be due to your cookies settings. See: https://github.com/gladly-team/next-firebase-auth/issues/351#issuecomment-991134374
