### ISSUE TITLE
How do I setup proper user permissions/access?

### ISSUE THREAD

**Issue by iamkratos** [gladly-team/next-firebase-auth#126]
I've setup the example site on my local machine, and right now, anyone can login into my app (whether they have an account or not). How can I setup criteria for onboarding new users (maybe they have to have a specific email url, or they can submit their signup info that I then approve through the firebase console, or an admin account on the site)?

Some context: I'm trying to build a dashboard for organizations, so I only want people within the organization to have access to their respective data. Would love to have tiers setup for dif users. Appreciate all recommendations and resources

**Comment by kmjennison** [comment]
This is out of scope for what this package does. Please look at Firebase docs or code repositories for guidance.

**Comment by iamkratos** [comment]
@kmjennison Thorough docs make any package better. Even if it's slightly out of scope, most people would want to know how to disable auto-signups, as that's not how other Firebase SDKs usually handle logins.

For anyone reading this, you can disable the auto-signup by changing your FirebaseAuth.js to this:
```
import React, { useEffect, useState } from 'react';
import StyledFirebaseAuth from 'react-firebaseui/StyledFirebaseAuth';
import firebase from 'firebase/app';
import 'firebase/auth';

// Note that next-firebase-auth inits Firebase for us,
// so we don't need to.

const firebaseAuthConfig = {
    signInFlow: 'popup',
    // Auth providers
    // https://github.com/firebase/firebaseui-web#configure-oauth-providers
    signInOptions: [
        {
            provider: firebase.auth.EmailAuthProvider.PROVIDER_ID,
            requireDisplayName: false,
        },
    ],
    signInSuccessUrl: '/dashboard',
    credentialHelper: 'none',
    disableSignUp: {
        status: true,
    },
    callbacks: {
        // https://github.com/firebase/firebaseui-web#signinsuccesswithauthresultauthresult-redirecturl
        signInSuccessWithAuthResult: () =>
            // Don't automatically redirect. We handle redirecting based on
            // auth state in withAuthComponent.js.
            false,
    },
};

const FirebaseAuth = () => {
    // Do not SSR FirebaseUI, because it is not supported.
    // https://github.com/firebase/firebaseui-web/issues/213
    const [renderAuth, setRenderAuth] = useState(false);
    useEffect(() => {
        if (typeof window !== 'undefined') {
            setRenderAuth(true);
        }
    }, []);
    return (
        <div>
            {renderAuth ? (
                <StyledFirebaseAuth
                    uiConfig={firebaseAuthConfig}
                    firebaseAuth={firebase.auth()}
                />
            ) : null}
        </div>
    );
};

export default FirebaseAuth;

```


More info on what's going on [here](https://github.com/firebase/firebaseui-web#configure-email-provider)
