### ISSUE TITLE
How can I get the already initialised Firebase Client SDK object?

### ISSUE THREAD

**Issue by shreyas-jadhav** [gladly-team/next-firebase-auth#127]
If this library initializes the firebase client SDK, so is there any way I could access the already initialised Firebase object to perform database/messaging or other operations through it, instead of initialising another object?

**Version**
0.13

**Comment by kmjennison** [comment]
Duplicate #113. See [this comment](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977) for an example.
