### ISSUE TITLE
RFC: making it easier to use the Firebase apps

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/next-firebase-auth#135]
Developers often need to access the Firebase JS app or admin app to use features beyond auth. Currently, our recommendation is to initialize the Firebase apps manually before initializing `next-firebase-auth` (see [this comment](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977) for one example). However, this recommendation has proven confusing: https://github.com/gladly-team/next-firebase-auth/discussions/61, https://github.com/gladly-team/next-firebase-auth/discussions/110, https://github.com/gladly-team/next-firebase-auth/issues/113

I'd love to find a way to support this use case without adding complexity to this package or extraneous props to higher-order functions. Recommendations are welcome here.

**Comment by kmjennison** [comment]
Version 0.13.1-alpha.0 adds a [`getFirebaseAdmin`](https://github.com/gladly-team/next-firebase-auth#getfirebaseadmin--appapp) method.

Adding a sibling method for the JS SDK, `getFirebase` (or `getFirebaseClient`?), seems like a reasonable solution.

**Comment by timfee** [comment]
Thank you 👍🏼 

For what it's worht, my my use case for `getFirebaseClient` is one where I'd use the auth'd user in a function to populate fields on the rendered page:

```ts
export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})(async ({ AuthUser }) => {
  const { id, email } = AuthUser
  const { data }  = await firebaseClient
    .firestore()
    .doc('/users/' + id)
    .get()

  return { props: { data, user: { id, email } } }
})

export default withAuthUser({})(Auth)
```

**Comment by timfee** [comment]
[commenting, take 2]

Thanks for this 👍🏼 

This is probably a result of me being not great at React (yet!), but:
```
export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})(async ({ AuthUser }) => {
  const { id, email } = AuthUser
  const { data } = await getFirebaseAdmin()
    .firestore()
    .doc('/users/' + id)
    .get()
  return { props: { data, user: { id, email } } }
})

export default withAuthUser({})(Auth)
```

Results in an error:
`Error: next-firebase-auth must be initialized before rendering.`

I may trying to do too many things at once here, but sharing the use case nevertheless.

Thanks!

**Comment by gavinharris-dev** [comment]
Was thinking of adding some documentation on using the firebase client. In one of my projects I'm using this library and also FB client for firestore and storage. Will make some notes and if I can make it make sense I'll create a PR.

**Comment by kmjennison** [comment]
Added [`getFirebaseClient` ](https://github.com/gladly-team/next-firebase-auth#getfirebaseclient--firebaseapp) in v0.13.1-alpha.1!

**Feedback welcome:** We might be ready to close this issue. Is anything missing here, or do you run into any problems? Do these new methods work for you?

For TypeScript users, I'd also appreciate verification that the types are correct (I haven't tested them myself).

**Comment by gavinharris-dev** [comment]
The only thing I was thinking was the name of this module? Should you rename now as this is providing more than just Firebase Auth?

**Comment by kmjennison** [comment]
@gavinharris-dev At this point, I don't think so. The real value and focus of this package is unified auth. Likely, the only features outside that scope will be the minimum needed so developers can use other Firebase services alongside it.

**Comment by timfee** [comment]
I noticed that using getFirebaseClient and getFirebaseAdmin don't get type hints; they are ultimately processed as `any`. 

I'm not a TypeScript expert, so I'm not sure if this is the right approach, but I was able to get the types working by manually importing the types in the `.d.ts` file:

```ts
import type FirebaseClientType from 'firebase/app'
import type FirebaseAdminType from 'firebase-admin'
```

and then using those types to annotate the return function:
```ts
export const getFirebaseAdmin: () => typeof FirebaseAdminType
export const getFirebaseClient: () =>  typeof FirebaseClientType
```

**Comment by timfee** [comment]
Also, I noticed the instruction:
```ts
 /* Add the Firebase products that you want to use 
    (note that this module imports `firebase/auth` already.
*/
```

I wonder if these additional modules could be passed in as params to the `getFirebaseClient` function, or possibly as a config option inside of the `init` function?

**Comment by kmjennison** [comment]
@timfee Just curious to understand how you're using this feature: what makes you want to use `getFirebaseClient` instead of importing the Firebase client directly?

I'm asking because, though the `getFirebaseClient` method is intended as an optional helper, I'm wondering if it'll actually cause more confusion than anything.

@gavinharris-dev -- would also welcome your thoughts on what problem `getFirebaseClient` solves.

**Comment by timfee** [comment]
> @timfee Just curious to understand how you're using this feature: what makes you want to use `getFirebaseClient` instead of importing the Firebase client directly?
> 
> I'm asking because, though the `getFirebaseClient` method is intended as an optional helper, I'm wondering if it'll actually cause more confusion than anything.

I was using it as a "helper" method to keep my imports tidy. I'm not an expert in all of this new-fangled import logic, but was assuming it would be more "efficient" to re-use any imports that the script provides. If there's no fundamental difference between calling `getFirebaseClient` and `import from firebase/app` then it may not be all that helpful after all.

One thing that I **could** see as a value-added shorthand would be actually returning a `FirebaseAdmin` object (in addition to `AuthUser`) for the SSR functions: 

```ts
export const getServerSideProps = withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN
})(async ({ AuthUser }) => {
  const UserRecord: UserType = (
    await getFirebaseAdmin().firestore().doc(`/users/${AuthUser.id}`).get()
  ).data()

  // ^^ would be nice to have an initialized Firebase[Admin] object for this. 

  const {
    uid,
    meta: { displayName, emailAddress, photoUrl }
  } = UserRecord

  return {
    props: {
      meta: {
        uid,
        displayName,
        emailAddress,
        photoUrl
      }
    }
  }
})
export default withAuthUser({})(Account)
```

But in the grand scheme of things, if using one of these re-exported helper methods has essentially the same performance/features/maintainability of a plain ol' direct import, I wouldn't be too sad if you removed.

**Comment by kmjennison** [comment]
@timfee Thanks for sharing!

> assuming it would be more "efficient" to re-use any imports that the script provides

I see. No, this doesn't provide any efficiency gains or reduction in code bundle size. This package already relies on your Firebase package as a peer dependency and will use that code. To the contrary, it's likely we'd make things more inefficient/bloated if this package were to try to manage Firebase imports.

>One thing that I could see as a value-added shorthand would be actually returning a FirebaseAdmin object 

Can you clarify how this differs from [`getFirebaseAdmin`](https://github.com/gladly-team/next-firebase-auth#getfirebaseadmin--firebaseadmin)?

**Comment by timfee** [comment]
> @timfee Thanks for sharing!

You bet! Thanks for responding :) 

> Can you clarify how this differs from [`getFirebaseAdmin`](https://github.com/gladly-team/next-firebase-auth#getfirebaseadmin--firebaseadmin)?

In hindsight, not a lot. :) Withdrawn!

**Comment by kmjennison** [comment]
The latest alpha release:
* removes `getFirebaseClient`
* changes the type definition of the `getFirebaseAdmin` return value (see [source](https://github.com/gladly-team/next-firebase-auth/blob/main/index.d.ts#L100)). This is a workaround, so I welcome a PR if there's a way to rely on the `firebase-admin` module for this type.

**Comment by dashreel** [comment]
@kmjennison is there a reason getFirebaseClient was removed?

I would like to use it instead of this for reactfire:

```
  <FirebaseAppProvider
      suspense
      firebaseApp={firebase.apps[0] || firebase.initializeApp(firebaseConfig)}
    >
      <SideMenuLayout>
        <Component {...pageProps} />
      </SideMenuLayout>
    </FirebaseAppProvider>
```

**Comment by kmjennison** [comment]
@dashreel It was removed because it's unnecessary and caused confusion. You can get the app from Firebase directly with ` import firebase from 'firebase/app'`. See the old [diff](https://github.com/gladly-team/next-firebase-auth/pull/170/files#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L9) and [docs](https://github.com/gladly-team/next-firebase-auth#using-the-firebase-apps) for examples.

**Comment by gavinharris-dev** [comment]
@kmjennison - I'm currently using the client side Firebase API in a project. Do you think it worth if I try and pull together an example that shows how I've do it (I'm currently using Firestore and Storage). Provide some pointers perhaps?

**Comment by kmjennison** [comment]
@gavinharris-dev Sure. We have a [tiny example of using Firestore](https://github.com/gladly-team/next-firebase-auth#using-the-firebase-apps) in the README, but additional docs are welcome.

**Comment by cechecco** [comment]
Hi, can you healp me? when i try to import getFirebaseAuth:
`import { getFirebaseAdmin } from 'next-firebase-auth'
VSC says: `import { getFirebaseAdmin } from 'next-firebase-auth'`
and the browser: `TypeError: (0 , next_firebase_auth__WEBPACK_IMPORTED_MODULE_1__.getFirebaseAdmin) is not a function`
I just copy-paste this example: https://github.com/gladly-team/next-firebase-auth#using-the-firebase-apps

**Comment by kmjennison** [comment]
@cechecco If you're using v1.0.0-canary.17, that method has been removed. Check out the v1.x docs:
https://github.com/gladly-team/next-firebase-auth/tree/v1.x

**Comment by cechecco** [comment]
So i can't use this function with firebase v9? if I use v^0.14.4 I got `TypeError: Cannot read properties of undefined (reading 'apps')` on `init` in `initAuth.js` this is because i use firebase v9?

**Comment by kmjennison** [comment]
@cechecco Correct. Instead, just use firebase-admin directly. See an example here:
https://github.com/gladly-team/next-firebase-auth/tree/v1.x#using-the-firebase-apps

**Comment by cechecco** [comment]
Hi, This is my server side code to fetch data from external service and save it in Firestore. On localhost it works but when I deploy it on Vercel, the page that use this code in getServerSideProps() return 500 error beacuse: The default Firebase app does not exist. Make sure you call initializeApp() before using any of the Firebase services.'

`
import { getApp } from "firebase-admin/app"
import { getFirestore } from "firebase-admin/firestore"

const fetchUserDataServer = async (...) => {
  const api = process.env....
  const token = process.env...
  const options = {headers: {'Authorization': `Bearer ${token}`}}
  const url = `${api}/${shorthand}`
  try {
    const res = await fetch(url, options)
    const report = await res.json()
  ...
...

export const findStoredReport = async (shorthand: string) => {
  let d = await (await getFirestore(getApp()).doc(...).get()).data()
  ...
}

export const requestFetchUserData = async (...) => {
  return (await findStoredReport(...)).status === 200 ? true : await fetchUserDataServer(...)
}`

**Comment by kmjennison** [comment]
@cechecco Can you confirm you're calling `init` to `next-firebase-auth` somewhere in the server-side code? That has to happen within your API route or whatever bundle is deployed to the backend.

**Comment by kmjennison** [comment]
See example API route:
https://github.com/gladly-team/next-firebase-auth/blob/v1.x/example/pages/api/example.js#L2-L4

**Comment by cechecco** [comment]
a thousand thanks. can you confirm that getFirebase of 'firebase-admin' cannot be used directly in a page even using getServerSideProps because also in this case the Firebase object is instantiated by the client? getFirebase of 'firebase-admin' can only be used in pages / api / (relative to a next.js project)

**Comment by kmjennison** [comment]
@cechecco No, that shouldn't be the case. You can use `firebase-admin` anywhere on the server as you normally would. However, you have to ensure you've initialized the Firebase admin app, either directly via `firebase-admin` or by calling `init` on `next-firebase-auth` with the Firebase admin information.

If you're still having trouble, please:
* Try the example app with your own Firebase configuration
* Create a repo with a minimal reproduction of the problem, then open a new discussion
