### ISSUE TITLE
Adding custom claims example

### ISSUE THREAD

**Issue by shreyas-jadhav** [gladly-team/next-firebase-auth#148]
How can I assign firebase roles to a user? I didn't find enough documentation. 
Can I have I can an idea how it's done? It's urgent.
**Version**
What version of `next-firebase-auth` are you using?
0.13.0-alpha.4

**Comment by litewarp** [comment]
Are you using the latest version? All custom claims should be available in the AuthUser instance (e.g., returned from `useAuthUser` under the key "claims"). On the server, you should be able to grab the claims normally through firebase admin.

**Comment by shreyas-jadhav** [comment]
But how do I set them in the first place?

**Comment by litewarp** [comment]
It would honestly have taken you less time to google "firebase custom claims" than post here. 

In any case, you should read the [firebase documentation](https://firebase.google.com/docs/auth/admin/custom-claims). This library is just an extension of firebase for the nextjs platform.

**Comment by shreyas-jadhav** [comment]
Please read my original question, since custom claims are now supported you must add an example snippet to the doc. Googling that will not give me results for next.js whether I can do that in api folder or firebase functions.
