### ISSUE TITLE
Update firebaseClientInitConfig TypeScript definition to support all Firebase JS SDK config properties

### ISSUE THREAD

**Issue by shreyas-jadhav** [gladly-team/next-firebase-auth#149]
**Describe the bug**
I am getting typescript error, I cannot add 
`storageBucket, messagingSenderId, and appId` to the `firebaseClientInitConfig`?
If I want to use FirebaseClient SDK I must pass the same object I passed in my app, but  `initAuth` doesn't let me add these params.

![image](https://user-images.githubusercontent.com/73429007/116517578-cbcead80-a8ec-11eb-88ff-d7eeaec570ed.png)

**Version**
0.13.0-alpha.0

**Expected behavior**
Allow to pass these params too, also I'm getting `process.env.NEXT_PUBLIC_FIREBASE_API_KEY` can be undefined error.

**Comment by maxzaleski** [comment]
Related to #147.

**Comment by gavinharris-dev** [comment]
I will take a look. Were you testing my fork? As the changes have yet to be merged into the main repo.

**Comment by kmjennison** [comment]
This seems like a problem with the TypeScript definition, not any other functionality. We pass the config object directly to `firebase.initializeApp` in [initFirebaseClientSDK.js](https://github.com/gladly-team/next-firebase-auth/blob/main/src/initFirebaseClientSDK.js#L13), so any properties supported by Firebase should work.

We should modify the [firebaseAdminInitConfig type](https://github.com/gladly-team/next-firebase-auth/blob/main/index.d.ts#L56) to use Firebase's JS SDK config type.

**Comment by kmjennison** [comment]
This is handled in #147 (not yet merged.)

**Comment by kmjennison** [comment]
Closed in #147.
