### ISSUE TITLE
AuthUser is not updating when using plain javascript for Auth.

### ISSUE THREAD

**Issue by shreyas-jadhav** [gladly-team/next-firebase-auth#150]
**Describe the bug**
I'm not using Firebase UI, i'm using vanilla javascript to sign in user (via phone auth), so when the user is signed in, I can confirm it in  `firebase.auth().currentUser`, but the `useAuthUser()` is not returning the user nor I can see a api request to login, as this is supposed to be done automatically when user's logs in.

```js
confirmResult.confirm(otp.current.value).then((result) => { 
    console.log(firebase,auth().currentUser); //this shows me user is logged successfully
}
```
useAuthUser() returns this:
```js
AuthUser 
{id: null, email: null, emailVerified: false, claims: {…}, getIdToken: ƒ, …}
claims: {}
clientInitialized: false
email: null
emailVerified: false
firebaseUser: null
getIdToken: ƒ ()
id: null
serialize: ƒ ()
signOut: ƒ ()
[[Prototype]]: Object
```

**Version**
0.13.1-alpha.0"

**To Reproduce**
1. Follow the [steps](https://firebase.google.com/docs/auth/web/phone-auth) for vanilla javascript phone auth - 
2. 
```js
const AuthUser = useAuthUser()
  useEffect(() => {
    console.log("AuthUser", AuthUser);
    //not changed even when user is logged
  }, [AuthUser])
```

**Expected behavior**
Automatically update AuthUser when user is logged

**Comment by kmjennison** [comment]
For anyone to help out here, this needs more info, ideally a repository with the simplest reproduction of the case. Closing until then.

One thing to double check is that you're using hooks within a functional React component.

Note that the method of signing in to the Firebase JS SDK should not have any effect on `next-firebase-auth`'s behavior.

**Comment by shreyas-jadhav** [comment]
Yes ofcourse I was using it in functional component, I realised i didn't export my component with `withAuthUser()(Component)` . Do you think an error message could be displayed if someone uses `useAuthUser` while not exporting component with `withAuthUser`. That'd be better.  :)

**Comment by kmjennison** [comment]
That makes sense. Opened #155

**Comment by krthush** [comment]
Ill second this, I think bit more clarity could have been added to the docs to "include the withAuthUser" for sign in so that the session is set correctly.
