### ISSUE TITLE
Question: how do I get Id token from signout request?

### ISSUE THREAD

**Issue by sergio-bravo** [gladly-team/next-firebase-auth#151]
The case is: I need to call `admin.auth().revokeRefreshTokens(uid)` at the sign out request.

The problems:
1. `tokenChangedHandler` only has a token at sign in and I can't set a header at sign out
2. It's said in readme `Future requests to SSR pages receive the user info and ID token from cookies`, but there is no example how to verify cookies, and `admin.auth().verifySessionCookie` fails to accept cookies I can take from `req` and there is no ID token in req.

**Comment by kmjennison** [comment]
Great question. Do you want to call `admin.auth().revokeRefreshTokens(uid)` only when the user _manually_ chooses to sign out via the UI, or any time the Firebase JS SDK returns an unauthenticated user? If the former, you could make your own API request prior to logout.

If the latter, I'm not sure what's the easiest approach at the moment. [Here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/withAuthUserTokenSSR.js#L58) is how we use cookies internally. As you noted, this package doesn't expose that logic or use the cookie values when setting/unsetting cookies. It's a bit messy, but you could parse and use cookie values yourself.

A few things to consider:
* The logout endpoint will rarely be called with auth cookies at all. This will only happen if the Firebase JS SDK signs the user out when cookies are still set (e.g., the user initiates a sign out, or the JS SDK storage was cleared but cookies were not, or the Firebase user was modified somehow on the backend).
* If you revoke the refresh tokens whenever one client calls the logout endpoint with cookies, the user will not have a valid refresh token on other clients (browsers / computers / browser profiles).

Just FYI, you can set a custom `tokenChangedHandler` to modify the logout request. I don't think it will help with this problem, but I wanted to share in case you see a way it helps your use case. See [config docs](https://github.com/gladly-team/next-firebase-auth#config) for that property and how it's used [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/useFirebaseUser.js#L55).

**Comment by sergio-bravo** [comment]
Hey @kmjennison, thank you for the reply.
I think I've found a quick workaround to `tokenChangedHandler`, at sign-in I memoise the token and then use it at sign-out.

But I'm not sure about `tokenChangedHandler` mechanics, would it always trigger at any `frebase.auth` state change?

**Comment by kmjennison** [comment]
@sergio-bravo It's triggered by `onIdTokenChanged` (source [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/useFirebaseUser.js#L82)).

**Comment by kmjennison** [comment]
Going to close this, but we can reopen if you run into problems.
