### ISSUE TITLE
InitConfig type does not include `debug: boolean` property

### ISSUE THREAD

**Issue by tlamarre91** [gladly-team/next-firebase-auth#157]
**Describe the bug**
In index.d.ts, the InitConfig type does not include the "debug" property, so you have to work around that to use the debug property in TypeScript.

**Version**
From my package.json:
```
    "cookies": "^0.8.0",
    "firebase": "^8.4.1",
    "firebase-admin": "^9.2.0",
    "next": "^10.0.0",
    "next-firebase-auth": "^0.13.1-alpha.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "react-firebaseui": "^5.0.2",
```

**To Reproduce**
1. In a TypeScript project, `import { init } from "next-firebase-auth"`.
2. Define an object `config` to be passed as argument to `init`.
3. Include a `debug: true` (or `debug: false`) property on `config`.
4. Try to call `init(config)`

**Expected behavior**
Object with `debug` property can be passed to `init`.

**Observed**
TypeScript error: `Argument of type '{ debug: boolean; ... }' is not assignable to parameter of type 'InitConfig'`

**Additional context**
The `debug` option does seem to work correctly! To work around this problem, you can say `const config: any` to disable type checking and pass it to `init`, but I think we'd rather not have to.

**Comment by kmjennison** [comment]
Closed in #158.
