### ISSUE TITLE
Persistence cookies with Auth Emulator in Development

### ISSUE THREAD

**Issue by AlexBrasileiro** [gladly-team/next-firebase-auth#160]
**Describe the bug**

_In development using the Auth Emulator_ both after creating the user `auth.createUserWithEmailAndPassword()` or attempting to login an existing user `auth.signInWithEmailAndPassword()` by refreshing the page that should be accessible only with logged users (_protected route, eg /profile_), the logout endpoint is always called, clearing the cookie and not persisting the logged in user.

**ps.** The described bug does not happen in production (using firebase hosting and cloud functions), in production everything works perfectly!!!

**Version**

0.13.1-alpha.1

**To Reproduce**

1. User tries to access the protected route (eg: _/profile_);
2. As he is not logged in yet, he is redirected to the login page (eg: _/profile/login_);
3. User logs in (or registers), cookies are created in the browser and is redirected to the protected route (eg: _/profile_);
4. So far everything works as expected, but if the user just refreshes the browser on this protected route, the cookies are automatically cleared and the user is redirected back to the login page, as if the user is no longer authenticated 😩

**Expected behavior**

That the authenticated user persists after the login or registration process to continue navigating the protected routes.

**Additional context**

Here are all the settings for the files in the project: (sorry if it got too long, just wanted to make sure that all relevant files were in scope 😅 )

```javascript
// utils/auth.js

import { init } from 'next-firebase-auth';

const IS_DEV = process.env.NODE_ENV === 'development';
const TWELVE_DAYS_IN_MS = 12 * 60 * 60 * 24 * 1000;

const initAuth = () => {

  let config = {
    authPageURL: '/profile/login',
    appPageURL: '/profile',
    loginAPIEndpoint: '/api/login',
    logoutAPIEndpoint: '/api/logout',
    firebaseAdminInitConfig: {
      // ...same of the README
    },
    firebaseClientInitConfig: {
      // ...same of the README
    },
    cookies: {
      name: 'ExampleApp',
      keys: [
        process.env.COOKIE_SECRET_CURRENT,
        process.env.COOKIE_SECRET_PREVIOUS
      ],
      httpOnly: true,
      maxAge: TWELVE_DAYS_IN_MS,
      overwrite: true,
      path: '/',
      sameSite: 'strict',
      secure: !IS_DEV,
      signed: true,
    }
  }

  if (IS_DEV) {
    config = {
      ...config,
      debug: true,
      firebaseAuthEmulatorHost: process.env.FIREBASE_AUTH_EMULATOR_HOST,
    }
  }

  init(config)

}

export default initAuth
```
--

```javascript
// ./_app.js

import initAuth from 'utils/auth';
initAuth()

  // ... rest of code 

export default App;
```
--

```javascript
// pages/api/login.js

import { setAuthCookies } from 'next-firebase-auth'
import initAuth  from 'utils/auth';

initAuth()

const handler = async (req, res) => {
  try {
    await setAuthCookies(req, res)
  } catch (e) {
    console.error(e)
    return res.status(500).json({ error: 'Unexpected error.' })
  }
  return res.status(200).json({ status: true })
}

export default handler
```
--

```javascript
// pages/api/logout.js

import { unsetAuthCookies } from 'next-firebase-auth'
import initAuth from 'utils/auth';

initAuth()

const handler = async (req, res) => {
  try {
    await unsetAuthCookies(req, res)
  } catch (e) {
    console.error(e)
    return res.status(500).json({ error: 'Unexpected error.' })
  }
  return res.status(200).json({ status: true })
}

export default handler
```
--

```javascript
// pages/profile/index.js

import {
  getFirebaseClient,
  AuthAction,
  withAuthUser
} from 'next-firebase-auth';

import 'firebase/auth';

const IS_DEV = process.env.NODE_ENV === 'development';
const MyLoader = () => <div>Loading...</div>

const Profile = () => {

   let auth = getFirebaseClient().auth();
   if (IS_DEV) auth.useEmulator('http://localhost:9099');
  
  const logout = () => {
    const user = auth.currentUser;
    if (user) auth.signOut()
  }

  return (
    <div>
      <h1>Profile</h1>
      <button onClick={logout}>Logout</button>
    </div>
  )

}

export default withAuthUser({
  whenAuthed: AuthAction.RENDER,
  whenUnauthedBeforeInit: AuthAction.SHOW_LOADER,
  whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
  LoaderComponent: MyLoader,
})(Profile);

```
--

```javascript
// pages/profile/login.js

import { 
  getFirebaseClient, 
  AuthAction, 
  withAuthUser 
} from 'next-firebase-auth';

import 'firebase/auth';

const IS_DEV = process.env.NODE_ENV === 'development';
const MyLoader = () => <div>Loading...</div>

const Login = () => {

  const emailRef_signin = useRef(null);
  const passwordRef_signin = useRef(null);
  const emailRef_signup = useRef(null);
  const passwordRef_signup = useRef(null);

  let auth = getFirebaseClient().auth();
  if (IS_DEV) auth.useEmulator('http://localhost:9099');

  const submitForm_signin = () => {
    auth.signInWithEmailAndPassword(emailRef_signin, passwordRef_signin).then((userCredential) => {
      console.log('userCredential', userCredential.user)
    }).catch((error) => console.log('userCredential error', error));
  }

  const submitForm_signup = () => {
    auth.createUserWithEmailAndPassword(emailRef_signup, passwordRef_signup).then((userCredential) => {
      console.log('userCredential', userCredential.user)
    }).catch((error) => console.log('userCredential error', error));
  }

  const logout = () => {
    const user = auth.currentUser
    if (user) auth.signOut()
  }

  return (
    <>
      <div>
        <h1>Sign In</h1>
        <form onSubmit={(e) => e.preventDefault()}>
          <input ref={emailRef_signin} type="text" placeholder="E-mail" />
          <input ref={passwordRef_signin} type="password" placeholder="Password" />
          <button onClick={submitForm_signin}>Sign In</button>
          <button onClick={logout}>Logout</button>
        </form>
      </div>
      <div>
        <h1>Sign Up</h1>
        <form onSubmit={(e) => e.preventDefault()}>
          <input ref={emailRef_signup} type="text" placeholder="E-mail" />
          <input ref={passwordRef_signup} type="password" placeholder="Password" />
          <button onClick={submitForm_signup}>Sign Up</button>
        </form>
      </div>
    </>
  )

}

export default withAuthUser({
  whenAuthed: AuthAction.REDIRECT_TO_APP,
  whenUnauthedBeforeInit: AuthAction.SHOW_LOADER,
  whenUnauthedAfterInit: AuthAction.RENDER,
  LoaderComponent: MyLoader,
})(Login)

```
--

Am I doing something wrong, or have I lost something in the settings? I really researched the issues a lot before creating this bug and tested a few different approaches without much success 😢

I appreciate any help or insights from what I may be setting up incorrectly o/

**Comment by kmjennison** [comment]
Can you confirm that the user is authenticated  by directly checking the Firebase JS SDK? This module [relies on Firebase's `onIdTokenChanged`](https://github.com/gladly-team/next-firebase-auth/blob/main/src/useFirebaseUser.js#L82) callback to know if the user is authed, so my guess is something is going wrong in your auth process (unrelated to this module).

If problem is specifically with server-side auth, check out this [troubleshooting info](https://github.com/gladly-team/next-firebase-auth#server-side-auth-is-not-working-the-user-and-token-are-always-null-when-using-withauthusertokenssr-but-client-side-auth-works) to make sure your cookie settings are correct.

**Comment by AlexBrasileiro** [comment]
Hey @kmjennison, thanks for your reply, I will try to reproduce as soon as possible, checking `Firebase's onIdTokenChanged` to see if something is wrong in the development phase.

I do not believe that the problem is about server-side auth, as commented at the beginning in Production everything is working correctly.

I will check if I am doing something wrong during development and let you know as soon as possible.

Thanks for the help,

**Comment by AlexBrasileiro** [comment]
@kmjennison perfect, I understand now what you mean. Even today I will test again and see if I am doing something incorrect by following your tips.

Once again I thank you for your help, I will take the weekend to complete these tests to close this issue as soon as possible.

**Comment by AlexBrasileiro** [comment]
@kmjennison 

I'm going to close this issue for now, I researched a lot and tried several different approaches (I tested all possible alternatives with cookies - `secure`, `sameSite`, and `path`), but as you commented it seems that the problem is in the Firebase Auth Emulator and not with this package.

In the [firebase-tools github](https://github.com/firebase/firebase-tools/issues?q=emulator+auth+refresh) many people have reported problems similar to the Auth Emulator, I will delve into other alternatives during the development phase (perhaps the option to start the Firebase APP on the client manually, instead of the your config used in the README ).

As I mentioned in production, everything is working perfectly, so probably the problem is with the Emulator and some configuration 😢

Thanks for the help anyway, if I find any solution, I'll post it here again in case anyone has the same problem.

**Comment by kmjennison** [comment]
@AlexBrasileiro Got it, thanks for putting in the work to investigate and for the update! Definitely keep us posted if you identify a problem.

**Comment by kmjennison** [comment]
Not sure if related, but [this comment](https://github.com/gladly-team/next-firebase-auth/issues/184#issuecomment-846465264) might be helpful about mismatches in the Firebase emulator host setting.

**Comment by KhudhurMD** [comment]
For me, the issue was because the environment variable: `FIREBASE_AUTH_EMULATOR_HOST` was not available to the client (only to the server). I've added a new variable named `NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST` with the same exact value and it worked!
