### ISSUE TITLE
Possible to use email links?

### ISSUE THREAD

**Issue by maerzhase** [gladly-team/next-firebase-auth#166]
I was wondering if it is at all possible to make a signin with email links. I successfully added the email link provider to the `FirebaseAuth` and I am also receiving the link via email. But when the link is opened the user is never authenticated. I couldn't find any explanation on how it should work or if it is considered a feature at all?!

**Comment by shreyas-jadhav** [comment]
Only thing I could suggest is to recheck if you are exporting the component with `withAuthUser()`
