### ISSUE TITLE
Handle additional errors from verifyIdToken

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/next-firebase-auth#174]
**Is your feature request related to a problem? Please describe.**

Firebase admin's `verifyIdToken` may throw some errors that this module should probably handle. See this thread for a background discussion: https://github.com/gladly-team/next-firebase-auth/pull/125

See a list of Firebase admin auth errors here:
https://firebase.google.com/docs/reference/node/firebase.auth.Error

Currently, we only handle `auth/id-token-expired`.

**Describe the solution you'd like and how you'd implement it**

When calling `verifyIdToken`, this module should probably handle the following errors:
* `auth/invalid-user-token`: return an unauthed user
* `auth/user-token-expired`: return an unauthed user
* `auth/user-disabled`: return an unauthed user
* `auth/argument-error`: call to refresh the ID token—however, we need to confirm this will address the `kid` claim error (see [this comment](https://github.com/gladly-team/next-firebase-auth/pull/125#issuecomment-815391594) for more info).

**Is this a breaking change?**
Yes, in the case developers are catching and handling these errors themselves.

**Describe alternatives you've considered**
Continue to ignore errors and let developers handle them. I can't think of a compelling reason _not_ to handle any of the above errors.

**Comment by alex-knyazev** [comment]
If understand correctly this is related to the described issue: 
![image](https://user-images.githubusercontent.com/15632220/143308400-c946c7cc-c703-4026-b0a6-4fb886dd57fa.png)

I think that firebase errors in `withAuthUserTokenSSR` should never be happened. We can have some special object with errors in AuthUser object.

**Comment by kmjennison** [comment]
Closed in #361.

**Comment by thanhtutzaw** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Firebase admin's `verifyIdToken` may throw some errors that this module should probably handle. See this thread for a background discussion: #125
> 
> See a list of Firebase admin auth errors here: https://firebase.google.com/docs/reference/node/firebase.auth.Error
> 
> Currently, we only handle `auth/id-token-expired`.
> 
> **Describe the solution you'd like and how you'd implement it**
> 
> When calling `verifyIdToken`, this module should probably handle the following errors:
> 
> * `auth/invalid-user-token`: return an unauthed user
> * `auth/user-token-expired`: return an unauthed user
> * `auth/user-disabled`: return an unauthed user
> * `auth/argument-error`: call to refresh the ID token—however, we need to confirm this will address the `kid` claim error (see [this comment](https://github.com/gladly-team/next-firebase-auth/pull/125#issuecomment-815391594) for more info).
> 
> **Is this a breaking change?** Yes, in the case developers are catching and handling these errors themselves.
> 
> **Describe alternatives you've considered** Continue to ignore errors and let developers handle them. I can't think of a compelling reason _not_ to handle any of the above errors.

I have firebase admin auth/argument error with uid .  What should I do . This error only in my local environment.
