### ISSUE TITLE
bug: The firebaseUser logged in to the identity platform outputs ctx.AuthUser which is different from withAuthUserTokenSSR and withAuthUserSSR. 

### ISSUE THREAD

**Issue by u-yas** [gladly-team/next-firebase-auth#175]
**Describe the bug**
If a firebase user logged in to the google identity platform uses withAuthUserTokenSSR, a different sign_in_provier will be returned and the exact AuthUser will not be available.
However, when withAuthUserSSR is used, the expected firebaseUser information is output. 

**Version**
What version of `next-firebase-auth` are you using?

https://github.com/gladly-team/next-firebase-auth/commit/997b8f90a8b9b68d33380416ca4949d6818bb919
0.13.1-alpha.3
**To Reproduce**

please clone my forked repository
-> https://github.com/u-yas/next-firebase-auth
or add console.log(firebaseUser) into [verifyIdToken function](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L59-L61)
**Expected behavior**

use withAuthUserSSR (expected output)
```javascript
{
  "iss": "https://securetoken.google.com/<project>",
  "aud": "<project>",
  "auth_time": ~~,
  "user_id": "<user uid>",
  "sub": "<user sub uid>",
  "iat": ~~,
  "exp": ~~,
  "email": "<user email>",
  "email_verified": true, // ok
  "firebase": {
    "identities": {
      "email": [
        "<user uid>"
      ]
    },
    "sign_in_provider": "password", // The correct provider that should be
    "tenant": "<user tenantId>"
  },
  "uid": "<user uid>"
}
```
 use withAuthUserTokenSSR (unexpected output)
```javascript
{
  "iss": "https://securetoken.google.com/<project>",
  "aud": "<project>",
  "auth_time": ~~,
  "user_id": "<user uid>",
  "sub": "<user sub uid>",
  "iat": ~~,
  "exp": ~~,
 email_verified: false
  "firebase": {
    "identities": {},
    "sign_in_provider": "custom"　// Different providers are returned
  },
  "uid": "<user uid>"
}
```
**Additional context**

**Comment by shreyas-jadhav** [comment]
I don't understand. Could you please explain more in another way if possible.

**Comment by kmjennison** [comment]
@u-yas This is expected behavior. Server-side auth uses a custom token (see [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L90-L119)), which will differ from the client-side Firebase auth.
