### ISSUE TITLE
What are COOKIE_SECRET_CURRENT and COOKIE_SECRET_PREVIOUS in next-firebase-auth/example/.env.local.example?

### ISSUE THREAD

**Issue by 15077693d** [gladly-team/next-firebase-auth#178]
Where could I get these values?

**Comment by kmjennison** [comment]
See [docs on cookies settings](https://github.com/gladly-team/next-firebase-auth/blob/main/README.md#cookies), which links to [info in the `cookies` package](https://github.com/pillarjs/cookies#cookies--new-cookies-request-response--options--). The keys are secrets used to sign your cookies and should be secure, random strings.

**Comment by Izhaki** [comment]
@kmjennison 

To be honest, this is still not very clear. My user journey:

- Seen the [docs](docs on cookies settings).
- Read the the info in the [cookies package](https://github.com/pillarjs/cookies#cookies--new-cookies-request-response--options--).
- This links to a "a [Keygrip](https://www.npmjs.com/package/keygrip) object".

And I'm still not sure what should these be:
- Should we call `new Keygrip(["SEKRIT2", "SEKRIT1"])`? That doesn't seem right as this will return an object.
- Should we just put some random strings? Why the reference to the cookies package then?

Seems to me that it should just be random strings, but I might be wrong.

**Comment by kmjennison** [comment]
@Izhaki An array  of random strings is just fine, and that's what we use in the docs/example.

From [`cookies` docs](https://github.com/pillarjs/cookies#cookies--new-cookies-request-response--options--):

> A Keygrip object or an array of keys can optionally be passed as options.keys to enable cryptographic signing based on SHA1 HMAC, using rotated credentials

The reason we link to `cookies` is that it's handling all cookie logic, including signing. The underlying details, like what algorithm it's using to sign cookies, might matter to developers.

I welcome suggestions on how to improve docs here.
