### ISSUE TITLE
Request: Add complete example of the authentication flow

### ISSUE THREAD

**Issue by SocialBrothersDEV** [gladly-team/next-firebase-auth#181]
**Did you have difficulty using or understanding an aspect of `next-firebase-auth`?**
I did know how to setup the login and logout endpoint and how to get the user's information on both client- and serverside. However, i have no clue how to actually authenticate the user. Should i authenticate using the `firebase.auth()` library on the front-end and just send the firebase user ID as a `Authorization` header to my login endpoint? Because the documentation states that this library will handle the Authentication header automatically, which indicates that there is some sort of login method provided by the next-firebase-auth library, which is not the case i believe.

What i'm doing now: 
- Login on client side using firebase SDK
- Call my /auth/login endpoint with a custom `Authorization` header set to the firebase UID. 

When i am not calling my /login/auth endpoint, everything is working exactly the same. I can still retrieve the user on both client- and serverside. 

**What documentation would you like to add or change?**
Please provide a complete flow of the different authentication methods. A full login flow, a full logout flow and a full registration flow. 

**Version**

0.13.1-alpha.3

**Comment by kmjennison** [comment]
There's an [example app here](https://github.com/gladly-team/next-firebase-auth/tree/main/example) that has a [live demo](https://github.com/gladly-team/next-firebase-auth#demo).

This module automatically calls the login and logout endpoints when the authentication state changes, so you don't have to worry about doing it yourself. To make this clearer, I updated the [config documentation](https://github.com/gladly-team/next-firebase-auth#config) for `loginAPIEndpoint` from this

> The API endpoint to call when the auth state changes for an authenticated Firebase user.

to

> The API endpoint this module will call when the auth state changes for an authenticated Firebase user.

FYI, if you need to customize the behavior of how your app calls the login/logout endpoints, you can use `tokenChangedHandler`.
