### ISSUE TITLE
How to login and logout?

### ISSUE THREAD

**Issue by 15077693d** [gladly-team/next-firebase-auth#183]
I saw the example folder using firebaseui. How about I use custom login component? How to login and logout?

**Comment by shreyas-jadhav** [comment]
This would happen automatically when the auth state changes, assuming you are actually logging in and signing out via Firebase SDK methods.

**Comment by 15077693d** [comment]
So I need to use SDK methods too, then What is the function on api/login and api/logout?

**Comment by shreyas-jadhav** [comment]
That's for server side, setting and unsetting the cookies. They are called automatically, when users signs in or signs out, if I'm not wrong.
