### ISSUE TITLE
Ability to ignore the basePath for authPageURL and appPageURL redirects at a global level

### ISSUE THREAD

**Issue by hershmire** [gladly-team/next-firebase-auth#187]
**Is your feature request related to a problem? Please describe.**

I'd like the ability to globally exclude the basePath (if one is used for the app) when handling redirects for `authPageURL` and `appPageURL` for both SSR & CSR. A common use case is where you have multiple NextJS applications under the same domain. The apps are managed by a load balancer and you only want to maintain one login page in one of the apps. All other apps should be able to redirect to the login app and when authenticated, a redirect should be possible to return back to the previous application.

**Describe the solution you'd like and how you'd implement it**
Example scenario:

### App 1:
https://example.com/admin
Basepath: `/admin`

If unauthenticated should be able to redirect to App 2's login page – https://example.com/auth/login.

### App 2:
https://example.com/auth
Basepath: `/auth`
Login page: `/auth/login`

1. User navigates to https://example.com/auth (App 1)
2. User is unauthenticated, library redirects user to https://example.com/auth/login (App 2)
3. User successfully logs in and is redirected back to https://example.com/auth (App 1)

**Is this a breaking change?**
Depends on how it's implemented but my guess is no.

**Describe alternatives you've considered**
This can be accomplished with the current library but requires additional boilerplate for each page. Boilerplate example:

*admin/pages/index.js (App1)*
```js
import React from 'react'
import { useAuthUser, withAuthUser, withAuthUserSSR } from 'next-firebase-auth'

const AdminHome = () => {
  const AuthUser = useAuthUser()

  if (typeof window !== 'undefined') {
    if (!AuthUser?.id) {
      // User is unauthenticated, redirect to the other application's login page
      window.location.assign('/auth/login');
      return null;
    }
  }

  return (
    <div>
      Admin home page content
    </div>
  )
}

export const getServerSideProps = withAuthUserTokenSSR()(async (ctx) => {
  const { AuthUser } = ctx

  if (!AuthUser?.id) {
    // User is unauthenticated, redirect to the other application's login page
    return {
      redirect: {
        destination: '/auth/login',
        permanent: false,
        basePath: false,
      },
    }
  }
  
  // User is authenticated, show the page
  return {
    props: {},
  }
})

export default withAuthUser()(AdminHome)
```

**Comment by kmjennison** [comment]
Maybe could support object values for these settings:
```js
{
  url: '/my-auth-page',
  basePath: false
}
```

**Comment by kmjennison** [comment]
In the meantime, it should work to use the `redirects` functionality in next.config.js.

**Comment by hershmire** [comment]
@kmjennison I don't think it will based on this race condition issue I created 10 days back – https://github.com/gladly-team/next-firebase-auth/issues/189.

**Comment by kmjennison** [comment]
@hershmire Hadn't noticed you opened both issues! 😄 Thanks – just chimed in on #189.
