### ISSUE TITLE
Unable to set Firestore settings

### ISSUE THREAD

**Issue by beeirl** [gladly-team/next-firebase-auth#191]
**Describe the bug**
I am not able to set Firestore related settings e.g.
```
firebase.firestore().settings({
    ignoreUndefinedProperties: true,
})
```
without running into one of the following errors:
- Uncaught FirebaseError: Firestore has already been started and its settings can no longer be changed. You can only modify settings before calling any other methods on a Firestore object.
- FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app)

I tried to set them after calling `initAuth()` and also in the `_app.ts`.

**Version**
0.13.1

**Comment by kmjennison** [comment]
Does it work if you initialize Firebase yourself first, like in [this example](https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977)?

Are you calling Firestore anywhere else? This package doesn't interact with Firestore at all, and "You can only modify settings before calling any other methods on a Firestore object" seems to suggest your app invokes a Firestore method.

**Comment by kmjennison** [comment]
Closing until there's a reproduction or more info.
