### ISSUE TITLE
Setting of FIREBASE_PRIVATE_KEY for vercel needs update for new vercel UI

### ISSUE THREAD

**Issue by krthush** [gladly-team/next-firebase-auth#212]
**Did you have difficulty using or understanding an aspect of `next-firebase-auth`?**
Setting FIREBASE_PRIVATE_KEY  env on vercel through web ui 

**What documentation would you like to add or change?**
If possible, provide an example of the documentation you'd like to see.
Using the vercel UI now its possible add the key in just following manner (no need to single quotes):
![image](https://user-images.githubusercontent.com/33790334/122447066-42a62f80-cf9b-11eb-84a1-1332ac47ae45.png)

**Version**
What version of `next-firebase-auth` are you using?
^0.13.1

**Comment by kmjennison** [comment]
Closed in #385
