### ISSUE TITLE
Cookies Keys: Type 'string | undefined' is not assignable to type 'string'

### ISSUE THREAD

**Issue by mathcrln** [gladly-team/next-firebase-auth#226]
**Describe the bug**
For the cookies option, the "keys" property expects an array of strings. But the environment variables in Next.js are defined as string | undefined. So, even if they are defined, typescript sees it as a type error since they could be undefined. Since they can't be accessible on the client-side, there isn't even a possibility to short-circuit it to satisfy typescript type validation. 

```node
Type error: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
```

Is there any fix for that or am I doing something wrong?

**Version**
What version of `next-firebase-auth` are you using?
As of now, using `"next-firebase-auth": "^0.13.2"`

**To Reproduce**
- Fill the object parameter for the init function with the environment variables in a local environment.
- Make sure you are using typescript and the file is saved with .ts extension
- Make sure in your tsconfig compilerOptions, "strict" is set to "true".

**Expected behavior**
For the keys property to expect an array of `string | undefined` to appease typescript (since the env variables can be undefined) and instead throw an error if they need to be defined and aren't.

**Additional context**
I came across similar type validation issues for almost all of the other expected variables, but since most are available on the client-side, I could verify them and satisfy typescript. Not optimal, but at least it worked. Am I missing something?

**Comment by anthonyshew** [comment]
What you're seeing here is that `process.env` has a type on it that recognizes that it's possible that that variable may not get set.

As you can imagine, one could forget to declare the variable in question - or purposefully leave it out of the environment for some reason.

Therefore, it is appropriate for Typescript to mention that the variable can be a `string` - but it also could end up being `undefined` if it were to be left out of the `.env`.

If you'd like to tell Typescript to stop yelling at you for this, you can do something like: `process.env.YOUR_CONSTANT as string`. This tells Typescript "just this time, I want this variable to have a type of string." This forces the variable to have the type that you are declaring.

**Comment by mathcrln** [comment]
@anthonyshew Thank you for that! It solved my problem and I think it's slightly better than putting a @ts-ignore 😅, so I'll close this issue.
