### ISSUE TITLE
Module not found: Error: Can't resolve 'fast-crc32c'

### ISSUE THREAD

**Issue by iamkratos** [gladly-team/next-firebase-auth#235]
I've built an app in NextJS using this package. In development there are no errors being thrown, but when I try to build, I'm getting an error saying:  Module not found: Error: Can't resolve 'fast-crc32c' in /node_modules/hash-stream-validation'

After some googling, it seems that the issue is related to how the Firebase Admin package is setup, but my github commit tells me none of my getServerSideProps Firebase functions are causing it (none of them changed since the last successful deploy). Has any one else run into this issue?

**Comment by uncvrd** [comment]
@iamkratos Hey! Did you figure out this problem? I can't seem to deploy to `next-serverless` or `netlify` because of this issue. I see you closed the ticket but was curious if you found a solution

**Comment by uncvrd** [comment]
Ok I see your comment here https://github.com/firebase/firebase-admin-node/issues/84#issuecomment-884209274 ...I didn't have to run the `externals` update, just installed the two packages. Still seems kind of like a hack. Shouldn't we be able to find a way to resolve the admin library from the webpack build?
