### ISSUE TITLE
Unable to deploy this library on Netlify or next-serverless, cannot resolve 'fast-crc32c'

### ISSUE THREAD

**Issue by uncvrd** [gladly-team/next-firebase-auth#236]
**Describe the bug**
Unfortunately, it appears that this library cannot be built when the `next.config.js` defines a `target: serverless`. An error occurs stating the following:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'fast-crc32c' in '/Users/jordan/GitHub/next-firebase-auth/example/node_modules/hash-stream-validation'
```

Both `next-serverless` and `netlify` require defining the target as `serverless` to be deployed using their libraries/services. Apparently `target: serverless` deploys an individual lambda for each page that needs it and I guess the `firebase-admin` package that relies on `hash-stream-validation` expects a nodejs environment to execute properly and cannot be bundled with webpack? I'm not an expert but that's sort of what I've picked up and I hope someone with more knowledge in this area can pick up from here.

**Version**
0.13.2

**To Reproduce**
- Use the `example` directory found in this repo
- Add `target: serverless` to the `next.config.js`
- Run `npm run build`

**Expected behavior**
I expect to be able to build my project using `target: serverless` without errors so I can deploy on services such as Netlify or on `next-serverless`.

**Additional context**
I apologize as I do not have a solution for this issue, there was a ticket opened and promptly closed in this repo regarding the same problem with no resolution here:

https://github.com/gladly-team/next-firebase-auth/issues/235

Also a Discussion opened with no response here:

https://github.com/gladly-team/next-firebase-auth/discussions/225

So I figured I'd open this and actively contribute to figuring out the problem with others here. Please let me know what I can do to help!

---

Edit: As an aside, I suppose it makes sense right? When I install `firebase-admin` to my next app, it detects it's not a server environment so dependencies such as `fast-crc32c` are not installed in my `node_modules` like they are for an `express` app. That's why I receive the `Module not found` error. The question now is, how do we prevent webpack from throwing an error when attempting to build the project since it detects that missing dependency?

A workaround is to just manually install the `fast-crc32c` package, however this does not work well when sharing projects to team members as they'll need to manually install the packages after a traditional `npm install` ...just a thought.

**Comment by kmjennison** [comment]
I haven't looked at this closely yet, but it might be related to #207.

**Comment by Izhaki** [comment]
# Importing Node Dependencies in Client Builds

This is the same issue as in [this SO question](https://stackoverflow.com/questions/42920761/getting-an-issue-while-integrating-google-cloud-with-webpack) and the answer within applies here. `firebase-admin` gets bundled into client side code.

The same issue happens on my fork mentioned in #207 - this has nothing to do with the distribution.

Now, in normal (ie, not `serverless`) NextJS builds, NextJS removes the `getServerSideProps` block and **all its related dependencies** from client-side builds. 

I could not find anything about it in the docs or googling it, but a quick experiment reveals that this is not the case in  serverless builds.

# The Experiment

If you delete `example/api` and all the pages other than `_app` and `auth` (neither has any dependencies to server side code), a serverless build will work alright.

Soon as you add, say, `index.js`, a serverless build will fail. If you then remove

```
export const getServerSideProps = withAuthUserTokenSSR()()
```

and the `withAuthUserTokenSSR` import - it will build again.

The odd thing is that if you bring back `example/api/login.js` you get the same error, despite anything within `/api` being server-side code.

# Rationale?

I'm not sure a serverless build is the way to go here.

I don't know about Netlify, but at least if you deploy the example to Vercel everything works just fine - and there's no server involved (I'm not sure how this work though, maybe they extract the `getServerSideProps` part into a lambda function).

**Comment by Izhaki** [comment]
@uncvrd I would actually recommend filing this issue on the NextJS Repo.

**Comment by kmjennison** [comment]
Yes, it looks like `target: serverless` is discouraged now and even undocumented: https://github.com/vercel/next.js/issues/20790

Unless that changes in Next.js, I don't think we'll support it here.

**Comment by uncvrd** [comment]
No problem, thanks for looking in to it

**Comment by izio38** [comment]
@uncvrd I am using the serverless component : `@sls-next/serverless-component@3.2.0`.

And I ran into your issue. Did you found a solution in-order-to build the nextjs application into a serverless environment ?

Thanks.

**Comment by uncvrd** [comment]
@izio38 technically you can fork the project comment out any references to firebase-admin where it's imported (removing the local dependency of fb admin in your project too) and it'll build / deploy. 

OR you can just manually install the node dependencies required. But highly do not recommend as collaboration will be a pain as theyll not auto install with 'npm i'.

But I just switched to Vercel instead and it works great
