### ISSUE TITLE
After changing claims, user's claims are not updated

### ISSUE THREAD

**Issue by locona** [gladly-team/next-firebase-auth#244]
**Describe the bug**
After changing claims, user's claims are not updated

**Version**
v0.13.1-alpha.3

**To Reproduce**
1. Create a server-side function to update claims.
2. Call the prepared function and call the following on the frontend
```
const { claims } = uesAuthUser();
```

3. Claims will not be updated.

**Expected behavior**

I want the frontend useAuthUser claims to be updated after calling ` setCustomUserClaims` on the server side (like firebase functions).

**Additional context**

**Comment by locona** [comment]
Maybe there is a problem here.

https://github.com/gladly-team/next-firebase-auth/blob/main/src/withAuthUser.js#L58-L61

**Comment by shreyas-jadhav** [comment]
You need to call `AuthUser.getIdToken(true)`

This will refresh the instance and fetch latest claims.

**Comment by locona** [comment]
@shreyas-jadhav 

What I want to do is to change the claims of all members except myself.

````
AuthUser.getIdToken(true)
```

If I put the above in, won't I have to do it every time when rendering?
