### ISSUE TITLE
CallbackUrl after credential login use the wrong domain/URL from Vercel

### ISSUE THREAD

**Issue by heggemsnes** [gladly-team/next-firebase-auth#251]
**Describe the bug**
When trying to redirect correctly after logging in, I get redirected to the current deployment url in Vercel. I want to get redirected to the correct domain.

Example:

- https://musikk-i-skolen.vercel.app/logg-inn (Logging in here)
- https://musikk-i-skolen-r2t0djwyq-kult-byra.vercel.app (Get redirected here)

I want to be redirected to the specified domain, https://musikk-i-skolen.vercel.app/velkommen

```
// pages/logg-inn.js
...
signIn("password-login", {
            email,
            password,
            // The page where you want to redirect to after a
            // successful login
            callbackUrl: `${process.env.NEXT_PUBLIC_FRONTEND_URL}/velkommen`,
          })
...
```

Everything shows up correctly in the POST request (https://musikk-i-skolen.vercel.app/api/auth/callback/password-login?) with the correct callback url.

I am logged in afterwards if I manually go to the "production domain".

If you need I can help to create a temporary account. Nothing is live yet.

**Version**
3.27.3

**To Reproduce**
1. Create credential login project
2. Deploy to vercel
3. Set callbackUrl to same domain (window.location.origin or .env variable)
4. Login with a user
5. See that you are redirected to wrong domain

**Expected behavior**
Being redirected to the correct callback

**Additional context**

**Comment by kmjennison** [comment]
What is the value of `appPageURL` in your call to `init`? Can you confirm you're using [`withAuthUser`](https://github.com/gladly-team/next-firebase-auth#withauthuser-options-pagecomponent) and set `whenAuthed` to `AuthAction.REDIRECT_TO_APP` for that page?

I don't recognize the `signIn` code you provided, so this might a problem with other Firebase configuration or code outside this library.

**Comment by heggemsnes** [comment]
Sorry, wrong repo. This was for next-auth. My bad 🤦‍♂️
