### ISSUE TITLE
Using Firebase JS SDK does not automatically trigger login handler

### ISSUE THREAD

**Issue by jung-chang** [gladly-team/next-firebase-auth#257]
**Describe the bug**
Using Firebase JS SDK should automatically trigger login handler as described: https://github.com/gladly-team/next-firebase-auth/issues/67#issuecomment-778272928. Neither signInWithEmailAndPassword() nor signInWithPopup() trigger it.

**Version**
0.13.3-alpha.0

**To Reproduce**
Adding login.js to provided example project

```
import firebase from "firebase/app";
import { useState } from "react";

const LogInPage = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const onSubmit = async () => {
    try {
      const user = await firebase
        .auth()
        .signInWithEmailAndPassword(email, password);
      console.log(user);
    } catch (error) {
      console.error(error);
    }
  };

  const googleSignIn = async () => {
    const provider = new firebase.auth.GoogleAuthProvider();
    try {
      const result = await firebase.auth().signInWithPopup(provider);
      console.log(result);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <main>
      <form onSubmit={onSubmit}>
        <input
          value={email}
          type="email"
          onChange={(event) => setEmail(event.target.value)}
        />
        <input
          value={password}
          type="password"
          onChange={(event) => setPassword(event.target.value)}
        />
        <input type="submit" value="Log in" />
      </form>
      <button onClick={googleSignIn}>Google</button>
    </main>
  );
};

export default LogInPage;
```

**Additional context**
Similar issue: https://github.com/gladly-team/next-firebase-auth/issues/67. Made sure that this is set: NEXT_PUBLIC_COOKIE_SECURE=false

**Comment by kmjennison** [comment]
Please provide a reproduction if you can, or at least some more info.

* This page isn't wrapped in `withAuthUser`, so it won't redirect after login. Did you mean to use it?
* Where do you call `init`? What does your config look like?
* You're try/catch/logging the sign in code. Do you see any errors logged to console? 
* Do you see any errors in your terminal?
* Does the demo work without any of your customization? It is working here: https://nfa-example.vercel.app/
* Do you see a request fired to your login endpoint? If so, what does the response look like?
