### ISSUE TITLE
withAuthUserTokenSSR documentation about nextjs misleading

### ISSUE THREAD

**Issue by mihirgupta0900** [gladly-team/next-firebase-auth#264]
**Did you have difficulty using or understanding an aspect of `next-firebase-auth`?**
Please describe what was challenging.

**What documentation would you like to add or change?**
If possible, provide an example of the documentation you'd like to see.

In [withAuthUserTokenSSR](https://github.com/gladly-team/next-firebase-auth/#withauthusertokenssr-options-getserversidepropsfunc---authuser---) part of the documentation, the example shows that you can call an API route in `getServerSideProps`. Which is misleading as the NextJS [documentation](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering) says the exact opposite of that.

![image](https://user-images.githubusercontent.com/37367148/128568360-6e63d659-2aa7-4c09-849a-6f5704d73944.png)

**Version**
What version of `next-firebase-auth` are you using?

**Comment by kmjennison** [comment]
Thanks! Makes sense. I'd prefer to leave the API call as-is so that it's clear how to use an external API, but we can add some comments to make clear it's a demo.

**Comment by mihirgupta0900** [comment]
Wouldn't be better overall to add an external API route? If not, comments should be fine

> Thanks! Makes sense. I'd prefer to leave the API call as-is so that it's clear how to use an external API, but we can add some comments to make clear it's a demo.

**Comment by kmjennison** [comment]
I'd rather the example be self-contained and not rely on an external API, especially so we can demonstrate sending the ID token. But, let me know if you have another suggestion for an example API endpoint.

**Comment by kmjennison** [comment]
Closed in #386
