### ISSUE TITLE
Per-Page Layouts with AuthUser

### ISSUE THREAD

**Issue by arbejd** [gladly-team/next-firebase-auth#267]
**Did you have difficulty using or understanding an aspect of `next-firebase-auth`?**
Im having a bit of a problem doing [Per Page Layouts](https://nextjs.org/docs/basic-features/layouts#per-page-layouts). More specifically i need access to the AuthUser in my navbar, but i do not want the navbar on all pages.

- If i place the .getLayout at component level, the Higher Order component (WithAuthUserHOC) removes it.
- If i attach .getLayout to the higher order component itself, it doesnt look like its getting Server Side Rendered.
- I can do like the example where <Header> is repeated on every page, but this causes unmount/remount of the header when changing pages

**What documentation would you like to add or change?**
I would love an example on how to use stateful layouts that is server-side-rendered, if there is a way to do this.

**Version**
What version of `next-firebase-auth` are you using?
0.13.2

**Comment by kmjennison** [comment]
Could you try out [v0.13.3-alpha.1](https://github.com/gladly-team/next-firebase-auth/releases/tag/v0.13.3-alpha.1)? It adds static method hoisting and so should support `getLayout`.

**Comment by uncvrd** [comment]
Hey @arbejd as Kevin mentioned, I submitted a PR that adds static method hoisting which doesn't remove the static prop from your component allowing page layouts `withAuthUser`. It's documented here https://github.com/gladly-team/next-firebase-auth/issues/224 and I link out to the tutorial I followed from Adam Wathan for best practices. Good luck!

**Comment by arbejd** [comment]
Thank you for the quick response! I will try out  **v0.13.3-alpha.1** and look forward to it going in production!
