### ISSUE TITLE
Support force-refreshing token via getIdToken

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/next-firebase-auth#286]
**Is your feature request related to a problem? Please describe.**
After changing user claims, apps often want to force a token refresh. In Firebase, this is done [by passing `true` to `User.getIdToken`](https://firebase.google.com/docs/reference/js/auth.user.md#usergetidtoken).

This package's `getIdToken` doesn't currently support force-refreshing, which is confusing: see #250, #282

**Describe the solution you'd like and how you'd implement it**

Pass arguments from `AuthUser.getIdToken` to Firebase's `getIdToken()` [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/createAuthUser.js#L120).

**Is this a breaking change?**
No.

**Describe alternatives you've considered**
None.

**Comment by lott105** [comment]
This would be awesome!

**Comment by iamgbayer** [comment]
the possibility to force a token refresh is very useful, hope it be added 👍

**Comment by kmjennison** [comment]
Closed in #301.
