### ISSUE TITLE
Error handling for defaultTokenChangedHandler ?

### ISSUE THREAD

**Issue by shaileshiyer** [gladly-team/next-firebase-auth#298]
**Describe the bug**
I have been trying to setup auth in such a manner that a user whose email is not verified will not be allowed to login. For that purpose I have been checking the email verification status on the loginAPIendpoint. If the email verification fails then I send a 401 error response back to the client but once I send it back nextjs crashes with an error saying unhandled runtime exception.  I wanted to do error handling for this but I am not able to understand where to place my error handler. 

**Versions**

`next-firebase-auth` version: 0.13.3
Firebase JS SDK: 8.10
Next.js: 11.1.0

**To Reproduce**
1. Set up the loginAPIendpoint so that it returns an response with 401 status code.
2. Allow a user to login.
3. Nextjs crashes with an unhandled runtime exception.
```
Unhandled Runtime Error
Error: Received 401 response from login API endpoint: {"error":"Email Address not verified.Please Check Your Mail."}

Call Stack
        eval
        node_modules/next-firebase-auth/build/index.browser.js (1:9559)
        Generator.next
        <anonymous>
        asyncGeneratorStep
        node_modules/@babel/runtime/helpers/asyncToGenerator.js (3:0)
        _next
        node_modules/@babel/runtime/helpers/asyncToGenerator.js (25:0)
```
![NextjsFirebaseAuthError](https://user-images.githubusercontent.com/19362829/131972383-ea3cb5d6-ac63-4e8d-9b05-43b77405c401.jpg)

**Expected behavior**
Allowing for error handling on the authStatelistener on the client side with the default token change handler.

**Comment by kmjennison** [comment]
You'll have to specify a custom `tokenChangedHandler` (see [config](https://github.com/gladly-team/next-firebase-auth#config)). [Here's an example](https://github.com/gladly-team/tab-web/blob/master/src/utils/auth/initAuth.js#L22) from another app.
