### ISSUE TITLE
Getting TypeError: Cannot read property 'apps' of undefined During Setup

### ISSUE THREAD

**Issue by niln1** [gladly-team/next-firebase-auth#300]
**Describe the bug**
Getting TypeError: Cannot read property 'apps' of undefined During Setup

**Versions**
    "firebase": "^9.0.2",
    "firebase-admin": "^9.11.1",
    "next": "^11.1.2",
    "next-absolute-url": "^1.2.2",
    "next-firebase-auth": "^0.13.3",
    "react": "^17.0.2",
    "react-dom": "^17.0.2"

**Expected behavior**
during init auth, it shows
Unhandled Runtime Error
TypeError: Cannot read property 'apps' of undefined when doing the example code

Does it work with 9.0.2 yet?

**Comment by kmjennison** [comment]
You'll need to use `next-firebase-auth@canary` for Firebase 9. See [docs](https://github.com/gladly-team/next-firebase-auth#get-started).

**Comment by niln1** [comment]
thanks
