### ISSUE TITLE
FirebaseError: Firebase Storage: No default bucket found. Did you set the 'storageBucket' property when initializing the app? (storage/no-default-bucket)

### ISSUE THREAD

**Issue by huzaifah050** [gladly-team/next-firebase-auth#308]
**Description**

Whenever you use firebase storage with next firebase auth and you import initAuth  and initialize it in _app.js, it always throws this error _"FirebaseError: Firebase Storage: No default bucket found. Did you set the 'storageBucket' property when initializing the app? (storage/no-default-bucket)",_ but should ypu take the import & initialization away from the _app.js and import it in the individual pages, it works just fine. 

**Versions**
`next-firebase-auth` version: "next-firebase-auth": "^0.13.2",
Firebase JS SDK: "firebase": "^8.6.8",
Next.js: 		"next": "11.0.0",

**To Reproduce**
1. Set up a simple project following the docs and import initAuth(); in _app.js
2. Set up firebase storage
3.  Try uploading files to your Storage Bucket
4. You will encounter this error _"FirebaseError: Firebase Storage: No default bucket found. Did you set the 'storageBucket' property when initializing the app? (storage/no-default-bucket)"_

**Expected behavior**
You shouldn't see this error and you should be able to upload your file since your bucket is already setup, and it is evident here as it works fine when you take the initialization off _app.js and import them in their respective pages.

**Comment by kmjennison** [comment]
[Here's an approach](https://github.com/gladly-team/next-firebase-auth/discussions/266#discussioncomment-1144809) that worked for others.

**Comment by huzaifah050** [comment]
> [Here's an approach](https://github.com/gladly-team/next-firebase-auth/discussions/266#discussioncomment-1144809) that worked for others.

Didn't solve it for me. Hopefully,  I find a solution for it.

**Comment by kmjennison** [comment]
Closing until there's a reproduction that pinpoints a bug in this library.

**Comment by fsolarv22** [comment]
any idea how to solve it with firebase v9 and next-firebase-auth@canary?

**Comment by frediustcDev** [comment]
This is what worked for me
```js
import * as firebase from "firebase/app";
import "firebase/storage";

export const FIREBASE_CLIENT = firebase.default;

if (FIREBASE_CLIENT.apps.length === 0) {
  FIREBASE_CLIENT.initializeApp(FIREBASE_CONFIG);
}
export const STORAGE_CLIENT = FIREBASE_CLIENT.app().storage(
  process.env.NODE_ENV === "production"
    ? "gs://prodURL.appspot.com"
    : "gs://devURL.appspot.com"
);
```

This is the most important line
```js
export const STORAGE_CLIENT = FIREBASE_CLIENT.app().storage("gs://storageUrl.appspot.com");
```

**Comment by bryandandan** [comment]
This was my solution which worked like a charm for me
Step 1: Add your storage bucket string in the firebaseClientInitConfig property in the initAuth.js (your storage bucket string can be found in your firebase console in the storage tab)
```
firebaseClientInitConfig: {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY, // required
  authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
  projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  storageBucket: 'gs://xxxxxxx.appspot.com'
},
```

Step 2: Make sure to have the right imports
```
import firebase from 'firebase/app'
import 'firebase/firestore'
```

Step 3: Create the storage ref and use it
```
// Create a root reference
var storageRef = firebase.storage().ref()

// Create an image reference
var profilePictureRef = storageRef.child(`/users/profilePictures/${user.uid}`)

await profilePictureRef.putString(file.thumbUrl, 'data_url')
```

That's it!
Note that the above solution works for firebase 8, using the following doc as reference: https://firebase.google.com/docs/storage/web/upload-files#web-version-8

If you are using firebase 9, simply modify step 9 and follow the instructions here: https://firebase.google.com/docs/storage/web/upload-files#web-version-9

**Comment by AlexisBustamante** [comment]
> This was my solution which worked like a charm for me
> 
> Step 1: Add your storage bucket string in the firebaseClientInitConfig property in the initAuth.js (your storage bucket string can be found in your firebase console in the storage tab)
> 
> ```js
> firebaseClientInitConfig: {
>   apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY, // required
>   authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
>   databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
>   projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
>   storageBucket: 'gs://xxxxxxx.appspot.com'
> },
> ```
> 
> Step 2: Make sure to have the right imports
> 
> ```js
> import firebase from 'firebase/app'
> import 'firebase/firestore'
> ```
> 
> Step 3: Create the storage ref and use it
> 
> ```js
> // Create a root reference
> var storageRef = firebase.storage().ref()
> 
> // Create an image reference
> var profilePictureRef = storageRef.child(`/users/profilePictures/${user.uid}`)
> 
> await profilePictureRef.putString(file.thumbUrl, 'data_url')
> ```
> 
> That's it! Note that the above solution works for firebase 8, using the following doc as reference: https://firebase.google.com/docs/storage/web/upload-files#web-version-8
> 
> If you are using firebase 9, simply modify step 3 and follow the instructions here: https://firebase.google.com/docs/storage/web/upload-files#web-version-9

this work forme, thanks

**Comment by Priyankcoder** [comment]
> This was my solution which worked like a charm for me
> 
> Step 1: Add your storage bucket string in the firebaseClientInitConfig property in the initAuth.js (your storage bucket string can be found in your firebase console in the storage tab)
> 
> ```js
> firebaseClientInitConfig: {
>   apiKey: process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY, // required
>   authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
>   databaseURL: process.env.NEXT_PUBLIC_FIREBASE_DATABASE_URL,
>   projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
>   storageBucket: 'gs://xxxxxxx.appspot.com'
> },
> ```
> 
> Step 2: Make sure to have the right imports
> 
> ```js
> import firebase from 'firebase/app'
> import 'firebase/firestore'
> ```
> 
> Step 3: Create the storage ref and use it
> 
> ```js
> // Create a root reference
> var storageRef = firebase.storage().ref()
> 
> // Create an image reference
> var profilePictureRef = storageRef.child(`/users/profilePictures/${user.uid}`)
> 
> await profilePictureRef.putString(file.thumbUrl, 'data_url')
> ```
> 
> That's it! Note that the above solution works for firebase 8, using the following doc as reference: https://firebase.google.com/docs/storage/web/upload-files#web-version-8
> 
> If you are using firebase 9, simply modify step 3 and follow the instructions here: https://firebase.google.com/docs/storage/web/upload-files#web-version-9

It worked for me like a charm, same issue happened with databaseUrl. Thanks 😄 !
