### ISSUE TITLE
ctx is undefined when redirecting to login page

### ISSUE THREAD

**Issue by runnedrun** [gladly-team/next-firebase-auth#311]
**Describe the bug**
When I use the authPageURL option in withAuthUser or initAuth, the ctx property passed in the args is undefined. 

**Versions**

`next-firebase-auth` version: "^1.0.0-canary.1"
Firebase JS SDK: 9.0.2
Next.js: "11.1.2"

**To Reproduce**
pass authPageURL: ({ctx}) => console.log("context", ctx) as an option to withAuthUser or initAuth. 
ctx will be undefined 

**Expected behavior**
ctx should have the url, params etc, not be undefined

**Additional context**
none, thanks!

**Comment by kmjennison** [comment]
Thanks for the issue!

The `ctx` value will only be available server-side. On the client side, you can rely on `window`. Here's how the example app handles it:
https://github.com/gladly-team/next-firebase-auth/blob/main/example/utils/initAuth.js#L15

**Comment by runnedrun** [comment]
Ok thanks!
