### ISSUE TITLE
Custom claims not provided on first login

### ISSUE THREAD

**Issue by kmjennison** [gladly-team/next-firebase-auth#317]
### Discussed in https://github.com/gladly-team/next-firebase-auth/discussions/316

<div type='discussions-op-text'>

<sup>Originally posted by **beingadrian** October 14, 2021</sup>
Hi!

Recently I've run into an issue with tokens with custom claims. The claims do not seem to be passed by the plugin when recreating the tokens on the server side.

### Context

1. I log in and my back-end API sends back a custom token with custom claims
2. I call Firebase's `signInWithCustomToken` and get an ID token back (this ID token has the claims)
3. On a different page, inside `withAuthUserTokenSSR` I call `AuthUser.getIdToken` and I get an ID token back (this ID token _does not_ have claims)
4. Given the missing claims, further authenticated requests to my back-end API will result in insufficient claims

### Investigation

After a little dive into the source code, I find the following line:
https://github.com/gladly-team/next-firebase-auth/blob/f42993567d499115dc0de0b3b581971d1bcfd0f9/src/firebaseAdmin.js#L96

Here it seems that the new tokens are only created with the user ID and the claims are not passed from the original ID token. 

Claims could be passed by adding the second parameter:
https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk

--

I'm not sure if I've missed something here, but please let me know if there's a way around this. 

Thank you!</div>

**Comment by amoo12** [comment]
Hi, is this issue solved yet?
I want to use this package but custom claims are important in my use case as I want to store user roles in custom claims and render role-based pages.
should I look for other solutions in this case?

**Comment by kmjennison** [comment]
No. A PR for this issue is welcome.

**Comment by kmjennison** [comment]
Closed in #660
