### ISSUE TITLE
Logging in causes " Error: Received 500 response from login API endpoint: {"error":"Unexpected error."} "

### ISSUE THREAD

**Issue by sabs21** [gladly-team/next-firebase-auth#318]
**Describe the bug**
When I try to login with new or existing credentials, I keep getting this error when landing on the auth page or just the normal homepage:
![image](https://user-images.githubusercontent.com/18126892/137524019-ccf99f26-e2f7-4dda-94b4-a36a31e7387e.png)
My team was able to signup/login without encountering this error. Also, I do get signed into my account that I've created, but I encounter this error.

**Versions**
`next-firebase-auth` version: 0.13.3
Firebase JS SDK: ^8.9.1
Next.js: 11.1.0

**To Reproduce**
1. I cloned this repo
2. Performed the command: cd ./next-firebase-auth/example
3. Performed the command: yarn
4. Setup my .env.local file
5. Performed the command: yarn dev
6. Clicked the login button
7. Entered credentials to sign up (and also logged in with those credentials later on)
8. Clicked "Sign In"
9. Would wind up on the "http://localhost:3000/auth" page and would get the error as shown in the image above.

**Expected behavior**
I expected to be able to login without any issues. Even when I did get an error, I didn't expect to be logged in after the error appeared.

**Additional Information**
I've tried these same steps on Brave, Chrome, and Edge with the same results.

**Comment by kmjennison** [comment]
The example API endpoint [logs the error](https://github.com/gladly-team/next-firebase-auth/blob/main/example/pages/api/login.js#L11). What is that error?

**Comment by sabs21** [comment]
@kmjennison Changing the email in the .env.local did the trick!

I thought that the email associated with my Google account was what I had to put there, but it turns out I needed to use the **service account** email instead.

Thank you!
