### ISSUE TITLE
getIdToken never refreshes the token client side

### ISSUE THREAD

**Issue by henryperson** [gladly-team/next-firebase-auth#319]
**Describe the bug**
It's possible this is an error on my side rather than with the package. However, I think my use case is pretty simple.

I'm making an authenticated API call server side and then making the same API call client side when a user wants to refresh data on the page. The API call is to a separate (non nextjs) backend. If I open the page, leave it open for about an hour without reloading the page, and then click my refresh data button, I get the following error on my backend when verifying the ID token: `ID token has expired at: 1634752738` (time changes obviously).

My API request is pretty simple, it's just
```javascript
authUser.getIdToken()
.then((token) => axios.get(url, {headers: { Authorization: token }}))
```
Unless I'm missing something, `getIdToken` should handle refreshing the token if it has expired, per the [firebase docs](https://firebase.google.com/docs/reference/js/auth.user.md#usergetidtokenresult). It does not appear to refresh the ID token ever—I am logging the token expiration date on my backend and it only changes when I reload the page, never when I make the request client side. Even when I pass `true` to force refresh the token, the expiration doesn't change and eventually it gives me an error.

Any idea why this might be happening?

**Versions**

`next-firebase-auth` version: `^0.13.4-alpha.0`
Firebase JS SDK: `^8.6.8`
Next.js: `11.0.1`

**Comment by kmjennison** [comment]
@henryperson I haven't been able to reproduce this.

[Here's my attempt](https://github.com/gladly-team/next-firebase-auth/pull/380/commits/cae12c7aafa4bc5bdef9ae3304893cc934174bb4). In a following commit, I enable force-refreshing the token during data fetch.

This is deployed here: https://nfa-example-dxp13iy31-gladly-team.vercel.app/
And data refetching here: https://nfa-example-dxp13iy31-gladly-team.vercel.app/static-auth-required-loader

You'll see the token changes each time you click "Debugging" and there's a new token sent each time you click "Refetch data". Server-side, I can confirm the expiration time is extended on each new request.

Thoughts? Is there anything I'm missing?

**Comment by kmjennison** [comment]
I also tested a version that does not force-refresh the token, refetching after an hour, and the token was automatically refreshed:
https://nfa-example-ipnbljou4-gladly-team.vercel.app/static-auth-required-loader

**Comment by kmjennison** [comment]
Closing until there's a clear way to reproduce.
