### ISSUE TITLE
Incompatible with next 12

### ISSUE THREAD

**Issue by VewMet** [gladly-team/next-firebase-auth#324]
**Describe the bug**
A clear and concise description of the bug.

**Versions**

`next-firebase-auth` version: 
Firebase JS SDK: 9
Next.js: 12.0.0

**To Reproduce**
npm install fails for next 12 version.

**Expected behavior**
Latest next version 12 comparability

Can we include in the roadmap?

**Comment by kmjennison** [comment]
Working on this now.
