### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'apps')

### ISSUE THREAD

**Issue by theunreal** [gladly-team/next-firebase-auth#343]
**Describe the bug**
I just created a nextjs TS app, trying to add firebase auth.
1. Added initAuth.js
2. `initAuth()` in _app.tsx
3. When accessing `http://localhost:3000` I get:
`Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'apps')`

![image](https://user-images.githubusercontent.com/6171883/143920128-f2a3b7fe-e030-4bb1-b10b-4f06b232caba.png)

**Versions**

`next-firebase-auth` version: 
Firebase JS SDK: 0.13.5
Next.js: 12

**To Reproduce**
already described

**Expected behavior**
no exception
**Additional context**
Typescript app

Anything I'm missing?

**Comment by theunreal** [comment]
Using canary did the trick

**Comment by abigoroth** [comment]
> canary
package.json

"next-firebase-auth": "1.0.0-canary.17",
