### ISSUE TITLE
Unhandled Runtime Error TypeError: Cannot read properties of undefined (reading 'apps')

### ISSUE THREAD

**Issue by AlaeddineMessadi** [gladly-team/next-firebase-auth#345]
**Describe the bug**
I was trying to follow the example provided.
When I dump the config object I see all the configuration values are correct.

the console: next-firebase-auth Setting config with provided value: {all correct values}

But always get the error `Cannot read properties of undefined (reading 'apps')`

**Versions**

`next-firebase-auth` version: **0.13.5-alpha.0**
`Firebase JS SDK`:  **9.5.0**
`Next.js`: **12.0.4**

**Comment by DragoshDX** [comment]
Hi. 
I believe that at this time the authentication package has not yet switched to the module version of Firebase that is 9+ 
I've seen conversations around here that it is to be fixed but I am also curious and following any information related to the issue. 

At this time I have not upgraded to Firebase 9 in my projects. If you want to use this package you can try installing an older version of firebase. Mine is 8.8.0.

Don't worry about potential issues with Firebase at this time, as the jump to 9 was mostly syntax stuff, going from old objects to tree shakeable modules, so you should be able to fly by with 8.x until the compatibility modes are updated or refactored to work with 9.x

**Comment by AlaeddineMessadi** [comment]
@DragoshDX Thank you for your reply. I downgraded **firebase**  to version `8.9.1` and it works fine now.

**Comment by kmjennison** [comment]
Firebase v9 is supported in `next-firebase-auth@canary`.
