### ISSUE TITLE
Allow for custom auth-state redirect configurations

### ISSUE THREAD

**Issue by offgriddev** [gladly-team/next-firebase-auth#350]
**Is your feature request related to a problem? Please describe.**
Currently there are only two kinds of redirects: REDIRECT_TO_APP and REDIRECT_TO_LOGIN. The logic for these redirects is hardcoded, which causes frustration for consumers who have requirements outside the hardcoded process.

This feature adds the ability to specify a custom redirect configuration for authenticated and unauthenticated users. It's currently a problem because there is little ability to control the attributes of a redirect when using the `withAuthUserTokenSSR` or `withAuthUser` modules. 

Currently, there are two ways redirects can work, and the logic is hardcoded into the components. 

1. Set the `authPageURL` and `whenUnauthed` to `AuthAction.REDIRECT_TO_LOGIN`, which handled an unauthenticated redirect. It will take the `authPageURL` from the component's parameters or from the config. With the `AuthAction.REDIRECT_TO_LOGIN` value, it needs a value for the auth page.
1. Set the `appPageURL` and `whenAuthed` to `AuthAction.REDIRECT_TO_APP`, which handled an authenticated user scenario. It will similarly take the `appPageURL` from config. 

Essentially, there is an assumption about the destination page and the auth state. When a user is unauthed, do A. When a user is authed, do B. But what if the an application or a particular instance of `withAuthUserTokenSSR` wants to map this differently? This is where we encounter our problem. There is a problem when consumers do not want the hardcoded redirect mappings. 

**Describe the solution you'd like and how you'd implement it**
Since our assumptions about authenticated or not don't need to change. I propose the solution to consumers, changing this:

```javascript
withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
  authPageURL: '/login',
})

withAuthUserTokenSSR({
  whenAuthed: AuthAction.REDIRECT_TO_APP,
  appPageURL: '/profile'
})
```

to this:

```javascript
withAuthUserTokenSSR({
  whenUnauthed: AuthAction.REDIRECT,
  onRedirect: {
    unauthenticated: {
      destination: '/login',
      permanent: false,
    }
  }
})

withAuthUser({
  whenAuthed: AuthAction.REDIRECT,
  onRedirect: {
    authenticated: {
      destination: '/profile',
      permanent: false,
    }
  }
})
```

The value for `unauthenticated` and `authenticated` are the redirect configs that can just be returned from the component. This configuration allows the user full control over the redirect from this vantage point. 

**Is this a breaking change?**
Would this require existing users to change how they're using `next-firebase-auth`?

No, you can easily support both versions side-by-side. I would only recommend you begin to refactor the code around redirects out into a separate file.

**Describe alternatives you've considered**

There were a couple other alternative implementations I was batting around, but they did not align with the concepts you've added in the codebase, so I added the AuthAction for a generalized `REDIRECT` value that does not denote a destination. I've aligned to the naming conventions here with `onRedirect` like `whenUnauthed`. Short of making our own redirect rules engine that parses a new structure, I think there's enough here to refactor a good amount of `withAuthUser` and `withAuthUserTokenSSR`.

**Comment by kmjennison** [comment]
@offgriddev Thanks for the detailed issue and PR.

I'm not understanding the problem your proposed changes address. Could you provide a few examples of something a developer might want to do that are impossible/difficult with the current configuration options?

I see that this approach allows configuring the `permanent` property of the server-side redirect, though I'm not sure that's too valuable for authed pages.

**Comment by offgriddev** [comment]
@kmjennison Sure thing. Thanks for hearing me out. This issue became more clear as I worked out a solution once I wrote the issue. 

You can see the problem of a developer who wants to set [any of the other properties of a redirect](https://nextjs.org/docs/api-reference/next.config.js/redirects), there is no way to do so. Currently, the paths to redirect are mapped to the following scenarios:
1. unauthed -> login page at the base path
2. authed -> app page at the base path

Scenarios like we are encountering are:
1. unauthed -> login page at a different base path

But you could also see a developer who may want to setup base path matching with `source` or add `locale`, there's no way to do it with just the auth states -> auth action. Since the redirects work generally the same for CSR/SSR, I think of this more as an option developers can employ for both scenarios. So while `permanent` might not be something desirable for SSR, other properties could be. The `AuthAction.REDIRECT` allows for any custom redirect scenario and can be used at any of the auth states, authed, unauthed, before / after init, etc. Thinking about alternatives for our specific scenarios (#187), like what you suggest [here](https://github.com/gladly-team/next-firebase-auth/issues/187#issuecomment-854164651), I went exposing the redirect object for configuration given the two main auth states.

**Comment by kmjennison** [comment]
@offgriddev I think you're confusing static [redirects in the Next.js config](https://nextjs.org/docs/api-reference/next.config.js/redirects), which you linked to above, with the [redirect property in `getServerSideProps`](https://nextjs.org/docs/basic-features/data-fetching#getserversideprops-server-side-rendering), which only has `destination` and `permanent` properties.

**Comment by offgriddev** [comment]
@kmjennison Hey 👋🏼  I just sync'd with my team and we found a way to do this without overloading like this. I'm going to close this out and rework my PR.
