### ISSUE TITLE
Fatal Next app refresh token error when user removed from firebase

### ISSUE THREAD

**Issue by alex-knyazev** [gladly-team/next-firebase-auth#372]
**Describe the bug**

I logged in, so cookies contains auth data. 

Then I removed this user in firebase-emulator, refresh page and see this error: 
```
Server Error
Error: Problem refreshing token: {"error":{"code":400,"message":"INVALID_REFRESH_TOKEN","errors":[{"message":"INVALID_REFRESH_TOKEN","reason":"invalid","domain":"global"}]}}  
```

![image](https://user-images.githubusercontent.com/15632220/146434418-a026246e-cf70-4399-853f-fbf2dea6de2d.png)

**Versions**

`next-firebase-auth` version: 0.13.5 
Firebase JS SDK: 
Next.js: 11.1.2

**To Reproduce**
1. Login with some user
2. Remove this user from firebase
3. Go to next ap and update

**Expected behavior**
Need to logout user or have abity to manually catch the error

**Comment by kmjennison** [comment]
Thanks for the issue! This is solved in #368, which isn't yet released but should be in the next few days.
