### ISSUE TITLE
Redirecting from app page after setting "whenUnauthed: AuthAction.REDIRECT_TO_LOGIN"

### ISSUE THREAD

**Issue by ukanwat** [gladly-team/next-firebase-auth#404]
**Describe the bug**
when I set "whenUnauthed: AuthAction.REDIRECT_TO_LOGIN" in the app page ('/') , it redirects me to the auth screen irrespective of whether I'm signed in or not.

**Versions**

`next-firebase-auth` version: 0.13.4
Firebase JS SDK:  8.9.1
Next.js:  12.0.7

**To Reproduce**
1. Just set it up in your project.
2. set "whenUnauthed: AuthAction.REDIRECT_TO_LOGIN" in the app page ('/'

**Expected behavior**
Page shouldn't redirect

**Additional context**

**Comment by kmjennison** [comment]
The [live demo](https://nfa-example.vercel.app/) doesn't have this issue, and I'll need more info to be able to help:
* Can you provide a deployed reproduction of the issue?
* Do you see any other errors in your terminal, browser console, or server-side error log?
* Can you confirm the Firebase user is logged in on the client side?
* Are the auth cookies successfully set during login?

Closing this until there's more info.
