### ISSUE TITLE
First redirect after auth with getServerSide props is unauthenticated.

### ISSUE THREAD

**Issue by viperfx** [gladly-team/next-firebase-auth#410]
**Describe the bug**
I am finding that the cookie is not set for the first page after successful authentication. When using `withAuthUserTokenSSR` with `getServerSideProps` - only after a refresh does the server have the cookies set. 

**Versions**

`next-firebase-auth` version: 0.14.0
Firebase JS SDK: 8.9.1
Next.js: 12.0.7

**To Reproduce**
1. Auth with a provider like Github or email through firebase.
2. On redirect see the headers does not set cookie on first redirect

**Expected behavior**
First page after authentication redirect should set cookie and be authed. So called like `const idToken = await AuthUser.getIdToken()` will fetch the user on first visit.

**Additional context**

**Comment by kmjennison** [comment]
Is your cookie's `SameSite` set to `Strict`? See: https://github.com/gladly-team/next-firebase-auth/issues/351#issuecomment-991134374

**Comment by viperfx** [comment]
@kmjennison No it's currently set to 'lax'.

**Comment by kmjennison** [comment]
@viperfx Is `next-firebase-auth` running on the authentication page? It'll have to complete its login request to set cookies before the redirect. Do you see the login request fired after logging in?

I don't see this happening on the [demo app](https://nfa-example.vercel.app/), so I'll need more info on how to reproduce it.

**Comment by viperfx** [comment]
The auth page is very similar to the example actually. 


Here is my auth.js page.

```
import { withAuthUser, AuthAction } from 'next-firebase-auth'
import FirebaseAuth from '../components/FirebaseAuth'

const Auth = () => (
  <div>
    <h3>Sign in</h3>
    <div>
      <FirebaseAuth />
    </div>
  </div>
)

export default withAuthUser({
  whenAuthed: AuthAction.REDIRECT_TO_APP,
  whenUnauthedBeforeInit: AuthAction.RETURN_NULL,
  whenUnauthedAfterInit: AuthAction.RENDER,
})(Auth)
```

and in my index.js page (the page redirected to after login)
```
export default withAuthUser()(Page)

export const getServerSideProps = withAuthUserTokenSSR()(
  withSubdomain(async ({ currentUser, subdomainMetadata }) => {
    return {
      props: {
        currentUser,
        subdomainMetadata,
      },
    }
  })
)
```

The main difference is my withSubdomain wrapper. It's calling an external application API and adding to the context. The token is fetched via **getIdToken**. This is not populated to what I would on the first load. 

```
export function withSubdomain(gssp) {
  return async (context) => {
    const { req, AuthUser } = context
    context.currentUser = null
    context.subdomainMetadata = null
    const { subdomain, customDomain, isCustomDomain } = getSubdomain(req.headers.host)

    const isSiteFound = await prisma.team.findMany({
      where: isCustomDomain
        ? {
            customDomain: customDomain,
          }
        : {
            subdomain: subdomain,
          },
    })

    if (isSiteFound.length == 0) {
      return {
        notFound: true,
      }
    }

    const idToken = await AuthUser.getIdToken()

    if (idToken != null) {
      rwAPI.setHeader('authorization', `Bearer ${idToken}`)
      rwAPI.setHeader('auth-provider', `firebase`)
      const query = gql`
        query getCurrentUser {
          redwood {
            currentUser
          }
        }
      `
      const data = await rwAPI.request(query)
      context.currentUser = data?.redwood?.currentUser || null
    }

    const subdomainMetadata = await getSubdomainMetadata({
      subdomain,
      customDomain,
      context,
    })

    context.subdomainMetadata = subdomainMetadata

    return await gssp(context) // Continue on to call `getServerSideProps` logic
  }
}

export default withSubdomain
```

**Comment by kmjennison** [comment]
Could you try the example app without any other code changes? It uses an ID token on first SSR load here:
https://github.com/gladly-team/next-firebase-auth/blob/main/example/pages/ssr-auth-required.js#L48

This would help check that your other code additions aren't the issue.

**Comment by viperfx** [comment]
I gave the example a try locally but was unable to reproduce my issue there!

So back to square one - not sure what I am doing differently. Any suggestions?

**Comment by viperfx** [comment]
I have tried the following code in my index.js page.

```
export const getServerSideProps = withAuthUserTokenSSR({ whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN })(async ({ AuthUser, req }) => {
  const token = await AuthUser.getIdToken()
  console.log(token)
  return {
    props: {},
  }
})
```

Even in the above code that is the same as the link you gave above, the token is null after first redirect. On refresh - the token is printed.

**Comment by viperfx** [comment]
So I found the issue. I was using the signInSuccessWithAuthResult to do some async calls and using awaits.

I realized the example did not have an async callback. I was doing this:

`signInSuccessWithAuthResult: async (authResult) => {`

after removing the async keyword. I was able to get the token after first redirect.

Now the only issue is that I was using this method for doing some operations to create a new user on my database.

```
    signInSuccessWithAuthResult: (authResult) => {
      if (authResult.additionalUserInfo.isNewUser) {
        const { subdomain, customDomain, isCustomDomain } = getSubdomain(window.location.host)
        const mutation = gql`
          mutation checkAndCreateMembershipWithSubdomain($email: String!, $sub: String!, $name: String, $subdomain: String!) {
            checkAndCreateMembershipWithSubdomain(email: $email, sub: $sub, name: $name, subdomain: $subdomain) {
              __typename
            }
          }
        `
        await rwAPI.request(mutation, {
          subdomain,
          sub: authResult.user.uid,
          name: authResult.user?.displayName,
          email: authResult.user.email,
        })
      }
      return false
    },
```

Any suggestions how I can do something like this elsewhere or get the async call to work?

**Comment by kmjennison** [comment]
Right, that function has to return a boolean ([firebaseui-web docs](https://github.com/firebase/firebaseui-web#signinsuccesswithauthresultauthresult-redirecturl)). You could call your async function without using `await`, or use promise syntax. Or, you could listen for auth elsewhere and create the user then.
