### ISSUE TITLE
useAuthUser in layout Error

### ISSUE THREAD

**Issue by adithep** [gladly-team/next-firebase-auth#425]
**Describe the bug**
using `useAuthUser` in layout that is in `_app` used to work in canary up to `1.0.0-canary.3`. But `1.0.0-canary.4` and  `1.0.0-canary.5` Errors:

```
When using `useAuthUser`, the page must be wrapped in `withAuthUser`.
```

**Versions**

`next-firebase-auth` version: 1.0.0-canary.5
Firebase JS SDK: 9.6.6
Next.js: 12.0.10

**Expected behavior**
Can use `useAuthUser` in the layout.

**Additional context**
Not sure if bug or intentional, if intentional what is the new pattern to use `useAuthUser` in wrapped component?

**Comment by kmjennison** [comment]
This is expected behavior: #155. See [this comment](https://github.com/gladly-team/next-firebase-auth/issues/155#issuecomment-912809559) for approaches to using a layout page across the app.
