### ISSUE TITLE
No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).

### ISSUE THREAD

**Issue by camilo-mujica** [gladly-team/next-firebase-auth#426]
Hello! First of all thanks for this awesome library.

**Describe the bug**
I'm using with TypeScript, and I keep getting this error:

![image](https://user-images.githubusercontent.com/84539709/152829037-2dc4892d-2cec-4160-8560-01b708f5a6a1.png)

But it's supposed that the initAuth() in _app.tsx should do the work right? Thank you id advance!

**Versions**
v1

**To Reproduce**
Whenever I call firebase getApp()

**Comment by camilo-mujica** [comment]
I've also tried with **next-firebase-auth@0.14.1** and **firebase@8.9.1** and keep getting the same error.

PD: I'm using TypeScript

**Comment by kmjennison** [comment]
Can you provide a full reproduction? Does the example app ([v0.x](https://github.com/gladly-team/next-firebase-auth/tree/main/example) / [v1.x](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example)) work for you?

Double check your Firebase imports are appropriate for the version of Firebase you're using.

**Comment by camilo-mujica** [comment]
@kmjennison I'm really sorry, I guess I'm a little confused about firebase SDK. I just went over the README.MD file of the project and it says:
 _"It does not extend Firebase functionality beyond providing universal access to the authed user. **Use the Firebase admin SDK and Firebase JS SDK for any other needs.**"_

But in the FirebaseAuth.js file it says:

// Note that next-firebase-auth inits Firebase for us,
// so we don't need to.

So, my doubt is the following: Should I initialize firebase for any other tasks?

**Comment by camilo-mujica** [comment]
> Can you provide a full reproduction? Does the example app ([v0.x](https://github.com/gladly-team/next-firebase-auth/tree/main/example) / [v1.x](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example)) work for you?
> 
> Double check your Firebase imports are appropriate for the version of Firebase you're using.

Yes, it does work, but it happens the same when I run 

`console.log(firebase.app())`

So I'm guessing it must be that I need to initialize firebase for any other task besides authentication

**Comment by kmjennison** [comment]
No, you shouldn't need to initialize it yourself. Here's an example that uses the Firebase app in v9 of the Firebase JS SDK:
https://github.com/gladly-team/next-firebase-auth/tree/v1.x#using-the-firebase-apps

**Comment by kmjennison** [comment]
The _"It does not extend Firebase functionality..."_ part of the README is just stressing that this library doesn't add core functionality to Firebase.

**Comment by camilo-mujica** [comment]
> No, you shouldn't need to initialize it yourself. Here's an example that uses the Firebase app in v9 of the Firebase JS SDK: https://github.com/gladly-team/next-firebase-auth/tree/v1.x#using-the-firebase-apps

I just tested it with this example https://github.com/gladly-team/next-firebase-auth/tree/main/example

And I can do the signIn / signOut process, but when it comes to using the sdk, I keep getting the same message: 

![image](https://user-images.githubusercontent.com/84539709/152871817-2614c1a6-4f4e-4aec-9623-aaa3a8f91fa9.png)

**Comment by camilo-mujica** [comment]
> No, you shouldn't need to initialize it yourself. Here's an example that uses the Firebase app in v9 of the Firebase JS SDK: https://github.com/gladly-team/next-firebase-auth/tree/v1.x#using-the-firebase-apps

I think I figure it out. Effectiverly I was doing something wrong, since the call to ` console.log(firebase.app())` should be inside a useEffect, unless the page is SSR, otherwise it'll throw and error because, *surprise*, the call is happening in the server, not the client. 

Thank you very much for your time, and sorry for the silly issue!

**Comment by kmjennison** [comment]
Makes sense. Glad you figured it out! 🎊

**Comment by jonbattista** [comment]
Hello, I am trying to upgrade to Firebase 9.x as well. I am still calling the `initAuth()` in `_app.js` but `getApp()` isnt returning the `next-firebase-auth` initialized app:

```
FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
    at getApp (file:///Users/jon.battista/ltpro-frontend/node_modules/@firebase/app/dist/esm/index.esm2017.js:469:29)
    at eval (webpack-internal:///./pages/_app.js:36:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'app/no-app',
  customData: { appName: '[DEFAULT]' },
  page: '/app'
}```

**Comment by bryandandan** [comment]
> Hello, I am trying to upgrade to Firebase 9.x as well. I am still calling the `initAuth()` in `_app.js` but `getApp()` isnt returning the `next-firebase-auth` initialized app:
> 
> ```
> FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
>     at getApp (file:///Users/jon.battista/ltpro-frontend/node_modules/@firebase/app/dist/esm/index.esm2017.js:469:29)
>     at eval (webpack-internal:///./pages/_app.js:36:65)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
>   code: 'app/no-app',
>   customData: { appName: '[DEFAULT]' },
>   page: '/app'
> }
> ```
> 
> I am using `"next": "12.0.7"`, `"next-firebase-auth": "^1.0.0-canary.7"` and `"firebase": "^9.6.10"`

Did you solve it? @jonbattista

**Comment by jonbattista** [comment]
I got it working with:
- next-firebase-auth@1.0.0-canary.7
- next@12.0.10
- firebase@9.6.10
- react-firebaseui@6.0.0

Calling getApp() with v9 syntax: `const auth = getAuth(getApp());`

I dont recall the exact solution. I just nuked my package.json/package-lock.json and npm cache.
