### ISSUE TITLE
Usage without `firebaseAdminInitConfig` object in the config raises app/invalid-credential error

### ISSUE THREAD

**Issue by fabienheureux** [gladly-team/next-firebase-auth#438]
**Describe the bug**
When using the package without service account credentials, and without `firebaseAdminInitConfig` object in the config, firebase admin raises an error when `/api/login` is called. 
```
  errorInfo: {
    code: 'app/invalid-credential',
    message: 'Failed to determine project ID: Error while making request: getaddrinfo ENOTFOUND metadata.google.internal. Error code: ENOTFOUND'
  },
```

I think it might have with the fact that we spread `firebaseAdminInitConfig` here but we do not reuse the project id. https://github.com/gladly-team/next-firebase-auth/blob/77a6280133d95aa0cbce01f293d0267e35d9fc0b/src/initFirebaseAdminSDK.js#L16-L23

Maybe we could add a `projectId` entry to the package config that is then passed to both admin and client config objects ? 

**Versions**

`next-firebase-auth` version: v1.0.0-canary.7
Firebase JS SDK: 9.6.6
Next.js: 12.0.10

**To Reproduce**
I will create an example repo later this week

**Expected behavior**
`setAuthCookie` calls do not fail

**Comment by fabienheureux** [comment]
Note : adding 
```
firebaseAdminInitConfig: {
  projectId: "some-project-id"
}
```

in initAuth helps working around this issue

**Comment by kmjennison** [comment]
Thanks for the issue!

Is there Firebase documentation about needing a project ID when initializing with default credentials? I don't see it in the [docs](https://firebase.google.com/docs/admin/setup#initialize-sdk). However, a project ID is needed when [testing with gcloud credentials](https://firebase.google.com/docs/admin/setup#testing_with_gcloud_end_user_credentials). Is that where you're running into the problem?

**Comment by kmjennison** [comment]
Closing until there's more info.
