### ISSUE TITLE
Getting authenticated user in the server (API route)

### ISSUE THREAD

**Issue by theunreal** [gladly-team/next-firebase-auth#458]
I don't see any documentation and couldn't figure it out, how can get the authenticated user in the server?

I have a fetch request to my NextJS API, as far as I could see I have to:
1. send the token from the client using Auth header
2. Verify it in the server

But I don't want to send the header on each request (unless I have to) and verify the token in each request..

```
    switch (req.method) {
        case RequestMethod.POST:
            if (!req.headers.authorization) {
                res.json({error: 'NO_AUTH', success: false});
                return;
            }
            const token = getStringParam(req.headers.authorization)
            await verifyIdToken(token);
.....
...
....
```

I wonder if I can get the authenticated user in the server using cookie / any other method I'm missing since I see the token is inside the request cookie.
As far as I understand, the `withAuthUserSSR` hooks are helpful only in case I want to initially load data based on the logged in user. my goal is different - perform a GET/POST request that the user initiates, and save the action to the DB with the user UID (do I need to pass it in the request each time?).

So the question is - How I should get the authenticated user in my API routes?

**Comment by kmjennison** [comment]
Closed with additional documentation in #547. In addition, we've added a method to get the user from cookies in #516.
