### ISSUE TITLE
Multilanguage support? (Like in Japanese)

### ISSUE THREAD

**Issue by KeisukeNagakawa** [gladly-team/next-firebase-auth#461]
**Is your feature request related to a problem? Please describe.**
I have trouble chaning login UI of firebase from English to other language(as for me, Japanese).

**Describe the solution you'd like and how you'd implement it**
It would be great if I can change language with language parameter described in code or parameter in some extenral file.
These package as below seems good solution for similar problem.
https://www.npmjs.com/package/firebaseui-ja

**Is this a breaking change?**
Would this require existing users to change how they're using `next-firebase-auth`? 
-> I suppose No.

**Describe alternatives you've considered**
-> I did not come up to...

**Comment by KeisukeNagakawa** [comment]
![スクリーンショット 2022-04-25 17 21 13](https://user-images.githubusercontent.com/28346899/165049365-da6f69e2-f010-42e0-86a5-b1c65a5eedc5.png)

**Comment by kmjennison** [comment]
The UI is totally up to you, so you can use firebaseui-ja if you want. `next-firebase-auth` doesn't include or rely on any UI framework. It uses FirebaseUI only as part of the demo app.
