### ISSUE TITLE
verifyIdToken does not seems to work

### ISSUE THREAD

**Issue by KeisukeNagakawa** [gladly-team/next-firebase-auth#463]
**Describe the bug**
When I pass wrong token like "aaa" for `verifyIdToken` method, I expected it to cause error but it seems it does not causes error. Instead of causing error, `verifyIdToken` seems to return infomration as follows:
```
 {
    id: null,
    email: null,
    emailVerified: false,
    phoneNumber: null,
    displayName: null,
    photoURL: null,
    claims: {},
    getIdToken: [Function (anonymous)],
    clientInitialized: false,
    firebaseUser: null,
    signOut: [Function (anonymous)],
    serialize: [Function: serialize]
  }
```

**Versions**
`next-firebase-auth` version: 1.0.0-canary.8
Firebase JS SDK: ^9.6.1
Next.js: 12.0.7

**To Reproduce**
1. run this example: https://github.com/gladly-team/next-firebase-auth/blob/main/example/pages/api/example.js#L20
2. pass wrong token like "aaa" and see it not to cause error.

**Expected behavior**
causes error to be able to catch properly when not authed.

Thanks.

**Comment by kmjennison** [comment]
This is expected behavior. See this config property for handling errors:
https://github.com/gladly-team/next-firebase-auth#onverifytokenerror
