### ISSUE TITLE
Token in withAuthUserTokenSSR seems to be missing details compared to the client rendered version 

### ISSUE THREAD

**Issue by aidanbarrett** [gladly-team/next-firebase-auth#466]
**Describe the bug**

I'd like to be able to use the token in SSR to make calls to our API which also uses gip tokens for auth.

The token I get from `await AuthUser.getIdToken()` within `getServerSideProps` `withAuthUserTokenSSR` is invalid when trying to make requests.

The tokens I get client side are all fine and requests made with them have all succeeded.

I inspected the contents of the JWTs and the one generated client side contains more information than its server-side counterpart:

Contents of Client side JWT:
```json
{
  "iss": "https://securetoken.google.com/xxxx-yyyyy-12345",
  "aud": "xxxx-yyyyy-12345",
  "auth_time": 1651479061,
  "user_id": "abcstkLCsEy111MpciZ1RoY12345",
  "sub": "abcstkLCsEy111MpciZ1RoY12345",
  "iat": 1651479061,
  "exp": 1651482661,
  "email": "name@email.com",
  "email_verified": true,
  "firebase": {
    "identities": {
      "email": [
        "name@email.com"
      ]
    },
    "sign_in_provider": "password"
  }
}
```

Contents of SSR JTW:
```json
{
  "iss": "https://securetoken.google.com/xxxx-yyyyy-12345",
  "aud": "xxxx-yyyyy-12345",
  "auth_time": 1651479062,
  "user_id": "abcstkLCsEy111MpciZ1RoY12345",
  "sub": "abcstkLCsEy111MpciZ1RoY12345",
  "iat": 1651479062,
  "exp": 1651482662,
  "firebase": {
    "identities": {},
    "sign_in_provider": "custom"
  }
}
```

I have cookies set to sameSite: "lax" and secure: "false" while I'm running locally and I can see the cookies with the correct name from the config available in the response object in `getServerSideProps`.

**Versions**

`next-firebase-auth` version:  `v1.0.0-canary.8`
Firebase JS SDK:  `9.6.2`
Next.js: `12.0.7`

**To Reproduce**
1. Sign in and redirect to page that uses `getServerSideProps` and `withAuthUserTokenSSR`
2. Make a request with in `withAuthUserTokenSSR` e.g.
```js
export const getServerSideProps = withAuthUserTokenSSR({
    whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
    whenAuthed: AuthAction.RENDER,
    appPageURL: "/"
})(async ({AuthUser}) => {
    const token = await AuthUser.getIdToken()
    console.log({AuthUser})

    try {
        const response = await fetch('https://api-endpoint', {
            method: 'GET',
            headers: {
                Authorization: `GipIdToken ${token}`,
            },
        })
....
    return {
        props: {token}
    }
})
```

**Expected behavior**
I would expect the JWT on server-side to contain the same information as that on the client.

**Additional context**
No additional context.

Thanks! It's super convenient library even with just the client side stuff working for me at the moment.

**Comment by kmjennison** [comment]
This is expected: we need to use a custom token to be able to refresh it server-side when it expires (see code [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/firebaseAdmin.js#L143-L178)). However, we could [pass additional custom claims](https://firebase.google.com/docs/auth/admin/create-custom-tokens#create_custom_tokens_using_the_firebase_admin_sdk) to add, for example, `email` and `email_verified`.

@aidanbarrett When you say the token is "invalid", what's not working for you? Is your endpoint expecting an email property in the token?

**Comment by aidanbarrett** [comment]
Thanks for that @kmjennison. I've tracked down the problem.

The issue is that my endpoint is expecting the `tenantId` to be included in the token and I see that there is a PR (#429) open for tenanted workflows already.

Passing through custom claims could be a super handy feature though!
