### ISSUE TITLE
Measurement stopped working

### ISSUE THREAD

**Issue by rilmasaker** [gladly-team/next-firebase-auth#469]
**Describe the bug**
When I am doing `initAuth()` in `pages / _app`. Google analytics stopped working. Without `initAuth() `measurement works normally.
I don't know if it is necessary to add `measurmentId` to `init ({})`, but generally I don't know exactly where. Especially since I randomly added `measurmentId` to the object in many pleaces, but it didn't change anything.

**Versions**

`next-firebase-auth` version: ^1.0.0-canary.8
Firebase JS SDK: ^9.6.9
Next.js: latest

**Update:**
I just moved` init() `to useEffect  without dependencies in `_app.js` and it started working normally.

**Comment by davidwitten** [comment]
Thanks! I spent so long trying to debug this

**Comment by davidwitten** [comment]
That fix worked!

However, I now am running into an issue on pages using `withAuthUserTokenSSR({`

**Comment by kmjennison** [comment]
Thanks for the issue.

This library just passes the `firebaseClientInitConfig` to `firebase.initializeApp` (see [here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/initFirebaseClientSDK.js#L13)), so the config structure should be the same.

Are you spelling `measurementId` correctly? Your issue description is missing an "e".

@davidwitten It's totally fine to initialize Firebase yourself like you're doing. If an app is already initialized, the library will just use that app. Just curious, does this approach work for you? I'm wondering if the analytics have to be initialized before `next-firebase-auth` or if it doesn't matter.
```js
initAuth()
const firebaseApp = getApp()
const analytics = getAnalytics(firebaseApp)

function MyApp({ Component, pageProps }) {
    return <Component {...pageProps} />;
  }
```

**Comment by kmjennison** [comment]
We could initialize analytics automatically if `measurementId` is set in `firebaseClientInitConfig`. This would be a small change to in [initFirebaseClientSDK.js](https://github.com/gladly-team/next-firebase-auth/blob/main/src/initFirebaseClientSDK.js). My only concern if is it would increase bundle size to import `firebase/analytics`.

**Comment by rilmasaker** [comment]
@kmjennison I checked to spell, probably seven times, I was not this reason.

**Comment by davut** [comment]
Maybe adding `enable-analytics: true` inside `init` can be solution? @kmjennison

**Comment by kmjennison** [comment]
It's possible. As I mention above, we would just need to ensure that doesn't increase the bundle size for people who don't use the analytics functionality.

**Comment by davut** [comment]
Makes sense, is there any hack that we can do for now? 
```Javascript
initAuth()
const firebaseApp = getApp()
const analytics = getAnalytics(firebaseApp)
```
did not work for me.

**Comment by kmjennison** [comment]
@davut You can initialize Firebase yourself. Here is some example code:
https://github.com/gladly-team/next-firebase-auth/discussions/61#discussioncomment-323977

That isn't a "hack". This library initializes Firebase as a convenience, but it's totally fine to do it yourself to customize things.

**Comment by davut** [comment]
What if it firebase js version 9? 
is `import firebase from 'firebase/app'` same as `import firebase from 'firebase/compat/app'` ? I am still getting the some errors with the version 9 :/.

**Comment by kmjennison** [comment]
Closing this: apps should initialize Firebase themselves when additional Firebase init customization is required.
