### ISSUE TITLE
Sign out does not working properly in Firebase 9

### ISSUE THREAD

**Issue by mastepanoski** [gladly-team/next-firebase-auth#475]
**Describe the bug**
I tried to sign out using AuthUser.signOut() and it doesn't work (client and not SSR).

**Versions**

`next-firebase-auth` version: 1.0.0-canary.8
firebase: 9.7.0
firebase-admin: 10.1.0
Next.js: 12.1.6
react: 18.1.0
react-dom: 18.1.0

**To Reproduce**
1. Login using email and password.
2. Create a signout page (for example /pages/signout.tsx

          import React from 'react'
          import type { NextPage } from 'next'
          import Head from 'next/head'
          import {
            withAuthUser,
            withAuthUserTokenSSR,
            AuthAction,
            useAuthUser,
          } from 'next-firebase-auth'
          import { isServerSide } from '@/utils/ssr'
          import { signOutUser } from '@/utils/auth/authClient'
          
          const SignOutPage: NextPage<unknown> = () => {
            const AuthUser = useAuthUser()
          
            const handleLogout = () => {
              if (AuthUser?.id) {
                // It is going to call the function defined at line 133 in https://github.com/gladly-team/next-firebase-auth/blob/main/src/createAuthUser.js
                AuthUser.signOut().then(() => {
                  alert('signed out')
                })
              }
            }
          
            React.useEffect(() => {
              if (!isServerSide()) {
                handleLogout()
              }
              // eslint-disable-next-line react-hooks/exhaustive-deps
            }, [AuthUser?.id])
          
            return (
              <div>
                <Head>
                  <title>sample</title>
                  <meta name="description" content="..." />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                <main>
                  <div>Loading...</div>
                </main>
              </div>
            )
          }
          
          export const getServerSideProps = withAuthUserTokenSSR({
            whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
          })()
          
          export default withAuthUser({
            whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
          })(SignOutPage)
3. Run /auth/signout in the browser.
4. You can see the alert message, but if you reload, the signout is triggered again, and if you go to a page that requires auth you can access to it and you won't be redirected to login.

**Expected behavior**

I expected that after executing /auth/signout the session would be closed, the cookie would be deleted, and the page would be redirected to login page.

**Additional context**

If I change the logout handler like this:

            import { getApp } from 'firebase/app'
            import { getAuth, signOut } from 'firebase/auth'

           ...

            const handleLogout = () => {
              if (AuthUser?.id) {
                const fbApp = getApp()
                const auth = getAuth(fbApp)
                signOut(auth).then(() => {
                  alert('signed out')
                })
              }
            }
  
           ...

So it works as expected.

**Comment by kmjennison** [comment]
Thanks for the issue. This is expected, because:
* The `signOut` method is a no-op when server-side or when the Firebase client has not yet initialized
* Your `useEffect` is only running when `id` changes, so it's missing updates and won't try to sign out after Firebase has initialized. That's the risk of your `// eslint-disable-next-line react-hooks/exhaustive-deps` :)

It will work if you include all dependencies in the `useEffect` / wait for `AuthUser.clientInitialized` to be true.

**Comment by mastepanoski** [comment]
Thanks, that it works now. It would be great if an example could be included in the README file, explaining how AuthUser related the firebase initialization cycle. For example:

      /* 3rd parties components & libraries */
      import React from 'react'
      import type { NextPage } from 'next'
      import Head from 'next/head'
      import {
        withAuthUser,
        withAuthUserTokenSSR,
        AuthAction,
        useAuthUser,
      } from 'next-firebase-auth'
      
      const SignOutPage: NextPage<unknown> = () => {
        const AuthUser = useAuthUser()
      
        React.useEffect(() => {
          // If the client-side Firebase JS SDK has been initialized and a user is currently logged in
          if (AuthUser.clientInitialized && AuthUser.id) {
              AuthUser.signOut()
                .then(() => {
                  console.log('signed out!')
                })
                .catch((err) => {
                  console.error('error signing out', err)
                })
          }
        }, [AuthUser, AuthUser.clientInitialized, AuthUser.id])
      
        return (
          <div>
            <Head>
              <title>Example</title>
              <meta name="description" content="..." />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
              <div>Loading...</div>
            </main>
          </div>
        )
      }
      
      export const getServerSideProps = withAuthUserTokenSSR({
        whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
      })()
      
      export default withAuthUser({
        whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN,
      })(SignOutPage)

**Comment by kmjennison** [comment]
Thanks for the example.

In general, I'd recommend a sign-out flow without a sign-out page, by just calling `signOut` from the parent page and managing the "in progress" UI with state. The downside of using a page is that another site could redirect or link to that page, causing your users to log out unknowingly.

**Comment by mastepanoski** [comment]
Yes that's true, the example is designed to be used in some alternative page in development mode, I don't intend to use it in production. However, it may happen that in some use cases, the developer wants to check some conditions and, if those conditions are not met, trigger a logout (for example, after mounting a page). I know it should be checked on the server side whenever possible, but there are very specific cases where conditions can include browser features, for example.
