### ISSUE TITLE
Private key setting in firebaseAdminInitConfig

### ISSUE THREAD

**Issue by DiyarS** [gladly-team/next-firebase-auth#49]
Hi! 

First of all, thank you for efforts and neat readable docs and example. 

I'm getting `Error: Invalid next-firebase-auth options: The "firebaseAdminInitConfig" private key setting should not be available on the client side.` error during initialization which is being called in my `pages/_app/index.tsx` file. The error is being raised in browser console. The private key is being set using environment variables. 

I've ran the example app and don't face same error there. I am building my app using [NextJS boilerplate](https://github.com/pankod/next-boilerplate). I am new to NextJS. 

Is there something wrong I am doing? Thanks in advance.

**Comment by kmjennison** [comment]
Hi, and thanks!

We expect `firebaseAdminInitConfig.credential.privateKey` to be falsy on the client side (see the [config validation here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/config.js#L85)). This is a precaution to make sure developers aren't accidentally bundling their private key with client-side JS.

Is your `firebaseAdminInitConfig.credential.privateKey` value `undefined` on the client side (e.g. if you log it to your browser console)?

**Comment by DiyarS** [comment]
> Hi, and thanks!
> 
> We expect `firebaseAdminInitConfig.credential.privateKey` to be falsy on the client side (see the [config validation here](https://github.com/gladly-team/next-firebase-auth/blob/main/src/config.js#L85)). This is a precaution to make sure developers aren't accidentally bundling their private key with client-side JS.
> 
> Is your `firebaseAdminInitConfig.credential.privateKey` value `undefined` on the client side (e.g. if you log it to your browser console)?

@kmjennison no, `firebaseAdminInitConfig.credential.privateKey` is NOT `undefined`. I think I've figured out what the issue was. The thing was that my private key variable was named `NEXT_PUBLIC_FIREBASE_PRIVATE_KEY`. I assume `NEXT_PUBLIC` sets a variable to be public on client side in Next. Again, I am new to Next and this might be the reason. Though, thank you very much for navigating me to the solution. No more errors anymore.

**Comment by kmjennison** [comment]
@DiyarS Glad to hear! Yes, that's correct, you should **not** use `NEXT_PUBLIC*` env vars for any sensitive info.
