### ISSUE TITLE
Missing Typescript type definitions for getUserFromCookies

### ISSUE THREAD

**Issue by briandonahue** [gladly-team/next-firebase-auth#528]
**Describe the bug**
New method added in #516 did not include Typescript type definition and therefore was not found when trying to import into a typescript module.

**Versions**

`next-firebase-auth` version:  v1.0.0-canary.14
Firebase JS SDK: 
Next.js: 

**To Reproduce**
1. Add `canary` version of `next-firebase-auth`2. 
2. try to import `getUserFromCookies` from server-side code - not found3. 

**Expected behavior**
Expect it to be available from Typescript as well as Javascript

I will be submitting a PR for this immediately after posting the issue.

**Comment by kmjennison** [comment]
Fixed in #529.
