### ISSUE TITLE
Any plans for typescript bindings?

### ISSUE THREAD

**Issue by cly** [gladly-team/next-firebase-auth#56]

**Comment by kmjennison** [comment]
Absolutely, and I welcome a PR for it.

**Comment by cly** [comment]
Thanks for the quick response. If no one gets to it in a few weeks I can take a crack at it.

**Comment by mimiqkz** [comment]
I will be following this

**Comment by chimericdream** [comment]
I just opened a pull request for this. As best I can tell, the type defs were pretty straightforward. Of course, that makes me a _little_ worried I missed something. But if nothing else, it's a starting point.

**Comment by kmjennison** [comment]
@chimericdream Thanks! Requested a few changes. I don't have much TS experience, so I'd love another set of eyes to review this.

**Comment by kmjennison** [comment]
Released in v0.12.1. @chimericdream, thanks for the contribution!
