### ISSUE TITLE
v1: Cannot access admin SDK while unauthenticated

### ISSUE THREAD

**Issue by strid408** [gladly-team/next-firebase-auth#573]
**Describe the bug**

When trying to access the admin SDK in getServerSideProps while unauthenticated the following error appears.

![Screenshot 2022-11-05 at 23 02 28](https://user-images.githubusercontent.com/22024105/200143033-738bde7f-41c2-4400-9255-98d496791d9f.png)

**Versions**

`next-firebase-auth` 1.0.0-canary.17: 
Firebase JS SDK: 9.9.1
Next.js: 12.2.3

**To Reproduce**
1. Clone example project from v1.x branch
2. Add getFirestore from 'firebase-admin/firestore' to getServerSideProps in index.js (root page)
```
export const getServerSideProps = withAuthUserTokenSSR()(() => {
  const firestore = getFirestore();
  return {
    props: {},
  }
})
```
3. See error

**Expected behavior**
Firebase admin SDK should be accessible inside getServerSideProps even though the client isn't authenticated.

**Additional context**
While authenticated, the admin SDK works as expected.

**Comment by kmjennison** [comment]
Thanks for the clear issue!

I was able to reproduce locally: when the user is authenticated, the default Firebase admin app appears to initialize as expected; when the user is not authenticated, I receive the same error (`FirebaseAppError: The default Firebase app does not exist.`). Note that to repro, you have to stop and restart the dev server between changes to make sure the Firebase admin state is cleared.

This debug log is present when it succeeds:
`next-firebase-auth: [init] Initialized the Firebase admin SDK.`

But that debug log isn't present when it fails, so we're not calling Firebase admin init [here](https://github.com/gladly-team/next-firebase-auth/blob/v1.x/src/initFirebaseAdminSDK.js#L31).

I believe the cause of this is that we only init Firebase admin on demand, like when we [verify the ID token](https://github.com/gladly-team/next-firebase-auth/blob/v1.x/src/firebaseAdmin.js#L69). That works for the package's authentication but will break under the use case described here.

This should be a quick fix by making sure  we always init the Firebase admin. We can add `initFirebaseAdminSDK` (from: `import initFirebaseAdminSDK from 'src/initFirebaseAdminSDK'`) at the top of `getUserFromCookies`:
https://github.com/gladly-team/next-firebase-auth/blob/v1.x/src/getUserFromCookies.js
