### ISSUE TITLE
Repost : login api 500 error in Local

### ISSUE THREAD

**Issue by thanhtutzaw** [gladly-team/next-firebase-auth#574]
![Screenshot (76)](https://user-images.githubusercontent.com/71011043/200152029-5355569e-0cdd-48b2-a7af-bd4bde7f90c6.png)

Reproduce Steps
1. install example app from [next-firebase-auth](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example)
2. add your firebase config
3. run in localhost
4. give me some comments you get this same error or not 

Problem
1. Only in Local , local machine #572 
2. It still work in netlify , env 
3. here it works https://too.netlify.app
4. doesn't redirect in local
5. doesn't create cookies ( cookies secure is fasle)
6. login api is pending in network
7. then status is 500

**my Env**

![carbon (1)](https://user-images.githubusercontent.com/71011043/200152449-912c18a5-3098-4abe-b282-cd6c9287d0aa.png)

**Comment by kmjennison** [comment]
Please stop spamming issues and discussions with the same content.
