### ISSUE TITLE
Allow installing next-firebase-auth in a Next v13 project

### ISSUE THREAD

**Issue by bourquep** [gladly-team/next-firebase-auth#585]
**Is your feature request related to a problem? Please describe.**

I have tried to `nom install next-firebase-auth` in a brand new NextJS v13 project, and it failed due to [this peer dependency constraint](https://github.com/gladly-team/next-firebase-auth/blob/main/package.json#L85).

**Describe the solution you'd like and how you'd implement it**

Although NextJS 13 introduces the new _app directory_ feature, this is opt-in only and there are no breaking changes in the other aspects of NextJS. I believe `next-firebase-auth` should be usable with NextJS 13 regular _pages_.

I suggest updating `next-firebase-auth`'s peer dependency to allow NextJS v13.

**Is this a breaking change?**

No

**Comment by kmjennison** [comment]
Thanks for the issue!
