### ISSUE TITLE
Use Emulator

### ISSUE THREAD

**Issue by FMGordillo** [gladly-team/next-firebase-auth#59]
**Is your feature request related to a problem? Please describe.**
When you have local/staging/prod environments, it gets quite tricky to test your changes (specially if you have Cloud Functions that handles the user creation (`functions.auth.user().onCreate()`).

**Describe the solution you'd like and how you'd implement it**
Currently `react-firebaseui` supports something like this:

```
        <StyledFirebaseAuth
          uiConfig={firebaseAuthConfig}
          firebaseAuth={
            process.env.NODE_ENV !== "production"
              ? firebase.auth().useEmulator("http://localhost:9099/")
              : firebase.auth()
          }
        />
```

But when I tried to use it, it breaks somewhere else:
![image](https://user-images.githubusercontent.com/7970174/106360782-3de92380-62f9-11eb-8e06-86ab0461958c.png)

**Is this a breaking change?**
I don't think so

**Describe alternatives you've considered**
I have no idea if there's any alternative

**Comment by kmjennison** [comment]
You can still initialize Firebase yourself (both JS SDK and admin SDK), before you call `initAuth`. When a Firebase app exists, this package will use it. Could you use the emulator that way?
