### ISSUE TITLE
Firebase JavaScript SDK 9.17.0 - 9.17.1 - Client side redirect not working.

### ISSUE THREAD

**Issue by tombouquet** [gladly-team/next-firebase-auth#612]
**When filing a bug report, please confirm you've done the following:**

1. Have you set `onVerifyTokenError` and `onTokenRefreshError` in your config and checked for any helpful errors?

**Yes**

2. Have you set `debug: true` in your config and read through server-side and client-side debug logs for any helpful messages?

**Yes**

3. Have you tried the [example app](https://github.com/gladly-team/next-firebase-auth/tree/v1.x/example) with your own Firebase credentials?

**Yes**

4. Have you read through the [troubleshooting](https://github.com/gladly-team/next-firebase-auth/tree/v1.x#troubleshooting) Q&A?

**Yes**

**Describe the bug**

Just a heads up that these versions do not work when using client side redirecting after a user has signed in. No errors in the console, debug or anything. Version 9.17.0 does have a [bug](https://firebase.google.com/support/release-notes/js#version_9170_-_february_2_2023) which is why it isn't working however it is fixed in 9.17.1, which is where the bug I am describing is occuring. I've just included it as an fyi for anyone.

I understand that devs can't always keep up with all the new versions of stuff. I just spent a long time trying to figure out why my app isn't working and didn't want anyone else to suffer the pain. 😊

**Versions**

`next-firebase-auth` version: canary.18
Firebase JS SDK: 9.17.0 - 9.17.1
Next.js: 13.1.6

**To Reproduce**
1. Make a sign in page (i've been using signInWithPopUp).
2. Add `withAuthUser` with the `whenAuthed` option to redirect to the app.
3. Login.
4. Done. The AuthUser var will not update. But if you add an onIdTokenChange func you can see that it actually does.

**Expected behavior**
When the user logs in the page redirects.

**Comment by kmjennison** [comment]
Thanks for the issue. Could you clarify: do you believe this is a bug in `next-firebase-auth` or just a bug in Firebase? Does this occur with older versions of the Firebase JS SDK?

**Comment by zerefati** [comment]
I am experiencing the same issue where upon logging in, the system displays a message indicating successful login, but fails to redirect to the designated application page URL until a manual refresh is performed.

**Comment by kmjennison** [comment]
Closing this until there's more info or a reproduction. FYI: any error could also be related to #614 .
