### ISSUE TITLE
Why is databaseURL required during init?

### ISSUE THREAD

**Issue by borisyordanov** [gladly-team/next-firebase-auth#634]
**Describe the bug**
I'm unable to provide the `databaseURL` the `init` function demands because I don't use Firebase's DBs. Passing an empty string silences the error and the library functions seemingly fine. It seems unnecessary for it to be required.

**Versions**

`next-firebase-auth` version: 1.0.0-canary.19
Firebase JS SDK: 9.19.1
Next.js: 13.2.1

**To Reproduce**
1. Call `init` in a TS file with a firebaseAdminInitConfig that's missing a `databaseURL` key
2. Expect a TS error about a missing key

**Expected behavior**
Firebase auth and the Firebase DB are separate services.  `next-firebase-auth` should not require information about a service that my Firebase project doesn't even use.

**Debug and error logs**
![image](https://user-images.githubusercontent.com/12392666/231402809-03eac12b-4549-4560-b775-839713de2872.png)

**Comment by kmjennison** [comment]
You're right, it shouldn't be required. Firebase docs show `databaseURL` as optional:
* JS SDK: [`initializeApp`](https://firebase.google.com/docs/reference/js/app.md#initializeapp_2) and [options interface](https://firebase.google.com/docs/reference/js/app.firebaseoptions.md#firebaseoptions_interface)
* Node admin SDK: [`initializeApp`](https://firebase.google.com/docs/reference/admin/node/firebase-admin.app#initializeapp) and [options interface](https://firebase.google.com/docs/reference/admin/node/firebase-admin.app.appoptions.md#appoptions_interface)

Please feel free to make a PR to update that type!
