### ISSUE TITLE
Improve setAuthCookies types to no be necessary passing an empty object when not setting the token

### ISSUE THREAD

**Issue by luiz504** [gladly-team/next-firebase-auth#684]
Following the `get started` documentation, the setAuthCookies function requires the `req` and `res` only, when playing this code using typescript it expects a third argument, that is a object that can receive a token property.
![image](https://github.com/gladly-team/next-firebase-auth/assets/53402833/92cc1d53-d89d-4dd7-abb5-1de26c99cc54)

I suggest to make the whole options object as optional to not be required passing a empty object when using the function without passing any options.
reviewing the source code, I guest that just add a "?" to the user property on the line 16 will solve it
![image](https://github.com/gladly-team/next-firebase-auth/assets/53402833/a8e07e98-19da-44c0-af93-5fce0fb97438)

**Comment by kmjennison** [comment]
Thanks for the issue! A fix will be out shortly.
