### ISSUE TITLE
Next 14 support

### ISSUE THREAD

**Issue by MvRemmerden** [gladly-team/next-firebase-auth#687]
Due to https://github.com/gladly-team/next-firebase-auth/blob/2c8f771e7ca286063b1b0afea9b8796832550728/package.json#L114, it's currently not possible to use next-firebase-auth with Next 14.

When looking at the breaking changes for Next 14, I don't see anything that should prevent next-firebase-auth to work, so would it be possible to allow upgrades to Next 14?

**Comment by kmjennison** [comment]
Releasing a version with this shortly. Thanks for the issue!
