### ISSUE TITLE
How to reduce bundle size?

### ISSUE THREAD

**Issue by Parnswir** [gladly-team/next-firebase-auth#80]
Thanks to your awesome package, I could finally get all of my firebase-auth-related use-cases to work in Next. However, I noticed the bundle size (aka `next build`'s "First Load JS shared by all") has doubled from ~64k to ~133k just by following the tutorial.

Is this common/expected? Can you point to any obvious mistakes one can make?

**Comment by kmjennison** [comment]
This package's built code is 10kb on the client side and 21kb on the server side, so that difference probably includes other dependencies. Can you analyze the bundles before/after to see what's added?
