### ISSUE TITLE
Typescript type definition has required fields marked as optional.

### ISSUE THREAD

**Issue by mrbrannan** [gladly-team/next-firebase-auth#89]
**Describe the bug**
The type definition for the interface `InitConfig` indicates that both `loginAPIEndpoint` and `logoutAPIEndpoint` are optional.

**Version**
What version of `next-firebase-auth` are you using?

`0.13.0-alpha.0`

**To Reproduce**

1. `yarn add next-firebase-auth`
2. Pass the `init` function a configuration object that is missing the keys in question.
3. Run the application.
4. Observe the error (and application failure) in console.

**Expected behavior**
When using `typescript` it is expected that the language will alert the developer that a required key is missing.

```
Type '{ authPageURL: string; appPageURL: string; firebaseAdminInitConfig: 
{ credential: { projectId: string; clientEmail: string; privateKey: string; }; databaseURL: string; }; 
firebaseClientInitConfig: { ...; };cookies: { ...; }; }'
is missing the following properties from type 'InitConfig': loginAPIEndpoint, logoutAPIEndpointts(2345)
```

**Additional context**
Super easy fix, I can create a PR if needed.

**Comment by kmjennison** [comment]
In fact, those fields are optional. The user can choose to set `tokenChangedHandler` and manage the API calls themselves, in which case they don't have to set `loginAPIEndpoint` and `logoutAPIEndpoint`.
