### ISSUE TITLE
Null Token Using withAuthUserTokenSSR

### ISSUE THREAD

**Issue by alteredorange** [gladly-team/next-firebase-auth#99]
**Describe the bug**
Token is always null when using getServerSideProps and withAuthUserTokenSSr

**Version**
0.13.0-alpha.0

**To Reproduce**
I'm using the basic setup from the docs and example site, trying to load some api data in server side props.
````
const Post = ({ post }) => { 
 return  <NewEdit content={post.content} title={post.title} pid={pid} id={1} />
  }
export const getServerSideProps = withAuthUserTokenSSR({
    whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,
})(async ({ AuthUser, params }) => {
    const { pid } = params
    console.log(pid)
    const token = await AuthUser.getIdToken()
    const response = await fetch(`http://localhost:3000/api/posts/${pid}`, {
        method: 'GET',
        headers: {
            Authorization: token || 'unauthenticated',
        },
    })
    const data = await response.json()
    return {
        props: {
            post: data
        }
    }
})
export default withAuthUser()(Post)

````

However, it always thinks I'm unautheticated, and redirects me to the login page (which then redirects me to my dashboard page because I'm already logged in).  If I comment out `whenUnauthed: AuthAction.REDIRECT_TO_LOGIN,`, I can see that the token is always null. So however it gets authed, (not sure if it's accessing cookies or what) doesn't seem to trigger.

If I don't use server side props, I'm able to get the token just fine:
````
const Post = ({ }) => {
    const AuthUser = useAuthUser()
    const getData = async (url) => {
        const token = await AuthUser.getIdToken()
        let res
        await fetch(url, {
            method: 'GET',
            headers: {
                Authorization: token,
            }
        }).then(async (r) => {
            // console.log(await r.json())
            res = await r.json()
        })
        return res
    }

    const { data: post, error } = useSWR(`/api/posts/${pid}`, getData)
 return      <NewEdit content={post.content} title={post.title} pid={pid} id={1} />

        
export default withAuthUser({ whenUnauthedBeforeInit: AuthAction.SHOW_LOADER, whenUnauthedAfterInit: AuthAction.REDIRECT_TO_LOGIN, LoaderComponent: FullPageLoader, })(Post)
````

Any help on getting serversideprops working would be greatly appreciated, thanks!

**Expected behavior**
Using `const token = await AuthUser.getIdToken()` would give the current user token.

**Comment by kmjennison** [comment]
@alteredorange Could you confirm the auth cookies are set in your browser's dev tools? If they're _not_ set, please check that the `secure`, `sameSite`, and `path` options passed in the `next-firebase-auth` config make sense for your environment. For example, if you're testing on non-HTTPS localhost, make sure `secure` is false.

**Comment by alteredorange** [comment]
@kmjennison Ah, sorry about that, it was indeed the `secure` option.  I bounced all over the docs for `getServerSideProps` and `SSR`, but didn't see the cookie bit. Might be work a * or () in the `withAuthUserTokenSSR` to mention checking cookies.  Thanks so much for the help, great plugin!

**Comment by zammitjames** [comment]
I've got the same issue. I'm using the canary version however the authToken is inconsistent. It sometimes shows up as null, and sometimes shows a value, but I've confirmed the cookies have been set successfully.
